// Generated by scripts/build-natural-parent-literature-batch-50.mjs --batch=50
import type { NaturalParentModification } from "./natural-parent-modifications";

export const naturalParentReviewBatch50: Record<string, NaturalParentModification> = {
  "200": {
    "reviewStatus": "complete",
    "naturalParent": "苯丙氨酸（CCD PHE）",
    "naturalParentCcd": "PHE",
    "relationship": "CCD明确把200关联到PHE母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个Cl（Cl连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个Cl（Cl连接到C）。相对天然母体：精确分子量+33.961 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.653。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.653、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "该非天然构件用于扩展肽的侧链、骨架或环化化学空间；对构象、稳定性和渗透性的实际影响取决于序列与位置。",
      "measurement": "PDB 3Q4K在DNA滑动夹结合短肽中记录CCD 200；该结构证明确有使用，但不单独证明口服、增渗或商业可得性。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 200 · 4-CHLORO-L-PHENYLALANINE",
        "url": "https://www.rcsb.org/ligand/200",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PHE · 天然母体",
        "url": "https://www.rcsb.org/ligand/PHE",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 3Q4K · DNA滑动夹结合短肽",
        "url": "https://www.rcsb.org/structure/3Q4K",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "A1A8T": {
    "reviewStatus": "complete",
    "naturalParent": "缬氨酸（CCD VAL）",
    "naturalParentCcd": "VAL",
    "relationship": "CCD明确把A1A8T关联到VAL母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C（C连接到C）。相对天然母体：精确分子量+14.016 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.39。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.39、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "下方另列原始论文实验；实验结论仍受肽序列和替换位置限制。"
    ],
    "peptideExperiment": {
      "conclusion": "蛋白酶稳定性 ↑；细胞抗病毒活性 ↑。该结果来自第4位Val的定点α-甲基化，且同一论文明确显示其他位置不一定受益。",
      "measurement": "在同一HIV-1大环肽中，第4位Val转换为α-甲基-L-Val后，人肝S9稳定性和细胞抗病毒活性均改善。论文没有证明αMeVal单独决定最终口服药代，因此仅作为位置依赖的直接稳定性证据。",
      "attributionBoundary": "按原论文记录实验对象和比较条件；若实验同时改变多个位点，结果只表示该残基可参与该性质变化，不能拆成固定的单残基增幅。",
      "confidence": "同骨架替换"
    },
    "sources": [
      {
        "title": "RCSB CCD A1A8T · 3-methyl-L-isovaline",
        "url": "https://www.rcsb.org/ligand/A1A8T",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD VAL · 天然母体",
        "url": "https://www.rcsb.org/ligand/VAL",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Kusumoto et al., ACS Medicinal Chemistry Letters, 2022",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9575168/",
        "supports": "提供性质实验和比较条件"
      }
    ]
  },
  "ABA": {
    "reviewStatus": "complete",
    "naturalParent": "丙氨酸（CCD ALA）",
    "naturalParentCcd": "ALA",
    "relationship": "CCD明确把ABA关联到ALA母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C（C连接到C）。相对天然母体：精确分子量+14.016 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.39。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.39、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "下方另列原始论文实验；实验结论仍受肽序列和替换位置限制。"
    ],
    "peptideExperiment": {
      "conclusion": "人血浆稳定性 ↑；DPP-4耐受性 ↑；同时保留显著的受体信号和降糖活性。该证据来自线性GLP-1类似物，不是环肽或口服药代实验。",
      "measurement": "Ala8→L-2-氨基丁酸的(Abu8)GLP-1在人血浆中的半衰期超过12小时；母体GLP-1约6.2小时。该类似物在细胞和肥胖糖尿病小鼠中仍显示胰岛素释放和降糖作用。",
      "attributionBoundary": "按原论文记录实验对象和比较条件；若实验同时改变多个位点，结果只表示该残基可参与该性质变化，不能拆成固定的单残基增幅。",
      "confidence": "同骨架替换"
    },
    "sources": [
      {
        "title": "RCSB CCD ABA · ALPHA-AMINOBUTYRIC ACID",
        "url": "https://www.rcsb.org/ligand/ABA",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD ALA · 天然母体",
        "url": "https://www.rcsb.org/ligand/ALA",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Green et al., Archives of Biochemistry and Biophysics, 2004",
        "url": "https://pubmed.ncbi.nlm.nih.gov/15246869/",
        "supports": "提供性质实验和比较条件"
      }
    ]
  },
  "AIB": {
    "reviewStatus": "complete",
    "naturalParent": "丙氨酸（CCD ALA）",
    "naturalParentCcd": "ALA",
    "relationship": "CCD明确把AIB关联到ALA母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C（C连接到C）。相对天然母体：精确分子量+14.016 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.39。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.39、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "下方另列原始论文实验；实验结论仍受肽序列和替换位置限制。"
    ],
    "peptideExperiment": {
      "conclusion": "构象刚性与分子内氢键 ↑；暴露极性和膜去溶剂化代价 ↓；柔性骨架中的被动渗透性、口服暴露和抗酶解性可 ↑；疏水性变化较小。",
      "measurement": "对多个 6–8 元环肽进行 Pro→Aib 替换后，柔性骨架的被动渗透性最高提高约 8 倍，并在小鼠中提高口服生物利用度；已高度预组织的骨架则未必受益。",
      "attributionBoundary": "按原论文记录实验对象和比较条件；若实验同时改变多个位点，结果只表示该残基可参与该性质变化，不能拆成固定的单残基增幅。",
      "confidence": "同骨架替换"
    },
    "sources": [
      {
        "title": "RCSB CCD AIB · ALPHA-AMINOISOBUTYRIC ACID",
        "url": "https://www.rcsb.org/ligand/AIB",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD ALA · 天然母体",
        "url": "https://www.rcsb.org/ligand/ALA",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Raj et al., Journal of Medicinal Chemistry, 2026",
        "url": "https://pubmed.ncbi.nlm.nih.gov/41797579/",
        "supports": "提供性质实验和比较条件"
      }
    ]
  },
  "3WX": {
    "reviewStatus": "complete",
    "naturalParent": "脯氨酸（CCD PRO）",
    "naturalParentCcd": "PRO",
    "relationship": "CCD明确把3WX关联到PRO母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C（C连接到C）。相对天然母体：精确分子量+14.016 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.39。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.39、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "下方另列原始论文实验；实验结论仍受肽序列和替换位置限制。"
    ],
    "peptideExperiment": {
      "conclusion": "蛋白酶稳定性 ↑；细胞抗病毒活性 ↑；可支持后续口服暴露优化。改善发生在特定大环肽第3位，不能外推到所有Pro位点。",
      "measurement": "同一HIV-1蛋白酶抑制大环系列中，将第3位Pro改为α-甲基-L-Pro提高了无NADPH的人肝S9稳定性并改善细胞抗病毒活性；作者指出其他位置的α-甲基化反而降低活性。后续保留该构件的化合物15和16在大鼠中获得可测口服生物利用度。",
      "attributionBoundary": "按原论文记录实验对象和比较条件；若实验同时改变多个位点，结果只表示该残基可参与该性质变化，不能拆成固定的单残基增幅。",
      "confidence": "同骨架替换"
    },
    "sources": [
      {
        "title": "RCSB CCD 3WX · 2-methyl-L-proline",
        "url": "https://www.rcsb.org/ligand/3WX",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PRO · 天然母体",
        "url": "https://www.rcsb.org/ligand/PRO",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Kusumoto et al., ACS Medicinal Chemistry Letters, 2022",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9575168/",
        "supports": "提供性质实验和比较条件"
      }
    ]
  },
  "5JP": {
    "reviewStatus": "complete",
    "naturalParent": "丝氨酸（CCD SER）",
    "naturalParentCcd": "SER",
    "relationship": "CCD明确把5JP关联到SER母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C（C连接到N）",
    "changedPosition": "新增基团连接到母体的氮原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C（C连接到N）。相对天然母体：精确分子量+14.016 Da，氢键供体0，氢键受体0，拓扑极性表面积-13.99 Å²，计算脂水分配系数+0.261。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积-13.99 Å²。",
      "计算趋势：脂水分配系数+0.261、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "下方另列原始论文实验；实验结论仍受肽序列和替换位置限制。"
    ],
    "peptideExperiment": {
      "conclusion": "骨架氢键供体 ↓；侧链羟基保留亲水性；水溶性通常优于疏水型 N-甲基残基；被动渗透性可达到中等水平，但低于 N-Me-Thr、N-Me-Ala 和疏水型 N-甲基残基。",
      "measurement": "在相同环六肽骨架的单点替换系列中，N-Me-Ser 类似物的 EPSA 为 83，RRCK Papp 为 1.6 × 10⁻⁶ cm/s。它证明了保留羟基的 N-甲基残基仍可支持可测的被动渗透，但不是该系列的最佳增渗残基。",
      "attributionBoundary": "按原论文记录实验对象和比较条件；若实验同时改变多个位点，结果只表示该残基可参与该性质变化，不能拆成固定的单残基增幅。",
      "confidence": "同骨架替换"
    },
    "sources": [
      {
        "title": "RCSB CCD 5JP · N-methyl-L-serine",
        "url": "https://www.rcsb.org/ligand/5JP",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD SER · 天然母体",
        "url": "https://www.rcsb.org/ligand/SER",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Goetz et al., ACS Medicinal Chemistry Letters, 2014",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4190640/",
        "supports": "提供性质实验和比较条件"
      }
    ]
  },
  "0A1": {
    "reviewStatus": "complete",
    "naturalParent": "酪氨酸（CCD TYR）",
    "naturalParentCcd": "TYR",
    "relationship": "CCD明确把0A1关联到TYR母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C（C连接到O）",
    "changedPosition": "新增基团连接到母体的氧原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C（C连接到O）。相对天然母体：精确分子量+14.016 Da，氢键供体-1，氢键受体0，拓扑极性表面积-11 Å²，计算脂水分配系数+0.303。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体-1、氢键受体0、极性表面积-11 Å²。",
      "计算趋势：脂水分配系数+0.303、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "酚羟基氢键供体被屏蔽；亲水性和暴露极性 ↓；疏水性与膜分配倾向 ↑；同时保留芳环用于疏水和 π 相互作用。",
      "measurement": "O-Me-Tyr 是口服 PCSK9 大环肽 enlicitide（Lipfendra，原 MK-0616）的六个非蛋白源残基之一。该药于 2026 年获 FDA 批准，但公开资料没有把 O-Me-Tyr 对吸收的贡献从三环骨架、其他残基和制剂中单独分离。",
      "attributionBoundary": "证据属于完整肽、天然产物、临床骨架或专利实例；只能说明该残基与该骨架相容，不能把整分子的性质归因于一个残基。",
      "confidence": "完整肽支持"
    },
    "sources": [
      {
        "title": "RCSB CCD 0A1 · O-methyl-L-tyrosine",
        "url": "https://www.rcsb.org/ligand/0A1",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TYR · 天然母体",
        "url": "https://www.rcsb.org/ligand/TYR",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Zhao et al., Precision Chemistry, 2026",
        "url": "https://doi.org/10.1021/prechem.5c00107",
        "supports": "提供完整肽或骨架层面的使用证据"
      },
      {
        "title": "U.S. FDA, Lipfendra (enlicitide) approval, 2026",
        "url": "https://www.fda.gov/news-events/press-announcements/fda-approves-first-oral-pcsk9-inhibitor-lower-ldl-cholesterol-adults-high-cholesterol",
        "supports": "补充完整骨架或临床证据"
      }
    ]
  },
  "A1AWS": {
    "reviewStatus": "complete",
    "naturalParent": "色氨酸（CCD TRP）",
    "naturalParentCcd": "TRP",
    "relationship": "CCD明确把A1AWS关联到TRP母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C、1个N（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C、1个N（C连接到C）。相对天然母体：精确分子量+24.995 Da，氢键供体0，氢键受体+1，拓扑极性表面积+23.79 Å²，计算脂水分配系数-0.128。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积+23.79 Å²。",
      "计算趋势：脂水分配系数-0.128、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "保留色氨酸样芳香侧链，同时自带可检测荧光，可用于无外接染料的细胞进入实验。",
      "measurement": "4CNW 被作为起始单体编入体外翻译的大环肽，用其内源荧光评估细胞通透性。研究证明其可被用于大环肽合成和检测，但没有证明 4CNW 本身提高通透性。",
      "attributionBoundary": "证据属于完整肽、天然产物、临床骨架或专利实例；只能说明该残基与该骨架相容，不能把整分子的性质归因于一个残基。",
      "confidence": "完整肽支持"
    },
    "sources": [
      {
        "title": "RCSB CCD A1AWS · 4-cyano-L-tryptophan",
        "url": "https://www.rcsb.org/ligand/A1AWS",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TRP · 天然母体",
        "url": "https://www.rcsb.org/ligand/TRP",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Huang et al., ChemMedChem, 2021",
        "url": "https://pubmed.ncbi.nlm.nih.gov/34236771/",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "BMT": {
    "reviewStatus": "complete",
    "naturalParent": "苏氨酸（CCD THR）",
    "naturalParentCcd": "THR",
    "relationship": "CCD明确把BMT关联到THR母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增6个C（C连接到C；C连接到N）",
    "changedPosition": "新增基团连接到母体的碳原子、氮原子",
    "structuralChange": "天然母体完整保留；检测到新增6个C（C连接到C；C连接到N）。相对天然母体：精确分子量+82.078 Da，氢键供体0，氢键受体0，拓扑极性表面积-13.99 Å²，计算脂水分配系数+1.843。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积-13.99 Å²。",
      "计算趋势：脂水分配系数+1.843、可旋转键+4、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "长烯基使疏水性与膜分配 ↑；N-甲基使骨架氢键供体 ↓；羟基保留一定亲水性；有利于分子内氢键和环境依赖折叠。单独增渗作用尚未证实。",
      "measurement": "MeBmt 是环孢素 A 的第 1 位特征非蛋白氨基酸，并被早期构效研究认为是药理活性所需残基之一。环孢素的人体口服吸收证明它可兼容高分子量口服环肽骨架，但不能据此判断 MeBmt 单独提高渗透性。",
      "attributionBoundary": "证据属于完整肽、天然产物、临床骨架或专利实例；只能说明该残基与该骨架相容，不能把整分子的性质归因于一个残基。",
      "confidence": "完整肽支持"
    },
    "sources": [
      {
        "title": "RCSB CCD BMT · 4-METHYL-4-[(E)-2-BUTENYL]-4,N-METHYL-THREONINE",
        "url": "https://www.rcsb.org/ligand/BMT",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD THR · 天然母体",
        "url": "https://www.rcsb.org/ligand/THR",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Wenger, Angewandte Chemie International Edition, 1985",
        "url": "https://doi.org/10.1002/anie.198500773",
        "supports": "提供完整肽或骨架层面的使用证据"
      },
      {
        "title": "Gupta & Benet, Biopharmaceutics & Drug Disposition, 1989",
        "url": "https://pubmed.ncbi.nlm.nih.gov/2611359/",
        "supports": "补充完整骨架或临床证据"
      }
    ]
  },
  "FCL": {
    "reviewStatus": "complete",
    "naturalParent": "苯丙氨酸（CCD PHE）",
    "naturalParentCcd": "PHE",
    "relationship": "CCD明确把FCL关联到PHE母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个Cl（Cl连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个Cl（Cl连接到C）。相对天然母体：精确分子量+33.961 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.653。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.653、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "芳香疏水性与膜分配倾向 ↑；氯取代可填充疏水口袋并阻断部分芳环代谢位点；亲水性 ↓；过多卤化可能降低溶解度。",
      "measurement": "口服 KRAS 环肽 LUNA18 的优化研究以 Phe(3-Cl) 芳香位点为重要中间设计，并通过侧链修改调节 ClogP、Caco-2 渗透性和细胞活性。公开结果支持卤代 Phe 用于疏水性/结合力联动优化，但单残基对口服吸收的贡献仍未拆分。",
      "attributionBoundary": "证据属于完整肽、天然产物、临床骨架或专利实例；只能说明该残基与该骨架相容，不能把整分子的性质归因于一个残基。",
      "confidence": "完整肽支持"
    },
    "sources": [
      {
        "title": "RCSB CCD FCL · 3-CHLORO-L-PHENYLALANINE",
        "url": "https://www.rcsb.org/ligand/FCL",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PHE · 天然母体",
        "url": "https://www.rcsb.org/ligand/PHE",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Tanada et al., Journal of the American Chemical Society, 2023",
        "url": "https://doi.org/10.1021/jacs.3c03886",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "HY3": {
    "reviewStatus": "complete",
    "naturalParent": "脯氨酸（CCD PRO）",
    "naturalParentCcd": "PRO",
    "relationship": "CCD明确把HY3关联到PRO母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个O（O连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个O（O连接到C）。相对天然母体：精确分子量+15.995 Da，氢键供体+1，氢键受体+1，拓扑极性表面积+20.23 Å²，计算脂水分配系数-1.029。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体+1、氢键受体+1、极性表面积+20.23 Å²。",
      "计算趋势：脂水分配系数-1.029、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "脯氨酸环限制局部构象；3-羟基提供氢键与成醚连接位点；形成分子内醚桥后可进一步固定三维构象，但不能把该位点视为游离羧酸型增溶残基。",
      "measurement": "enlicitide 的公开系统命名与合成路线显示该位点为 (3S)-3-hydroxy-L-proline，其羟基与邻近侧链形成分子内醚桥。人体口服数据支持这一交联构件可用于成功骨架，但没有 3-Hyp→Pro 的独立药代对照。",
      "attributionBoundary": "证据属于完整肽、天然产物、临床骨架或专利实例；只能说明该残基与该骨架相容，不能把整分子的性质归因于一个残基。",
      "confidence": "完整肽支持"
    },
    "sources": [
      {
        "title": "RCSB CCD HY3 · 3-HYDROXYPROLINE",
        "url": "https://www.rcsb.org/ligand/HY3",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PRO · 天然母体",
        "url": "https://www.rcsb.org/ligand/PRO",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Zhao et al., Precision Chemistry, 2026",
        "url": "https://doi.org/10.1021/prechem.5c00107",
        "supports": "提供完整肽或骨架层面的使用证据"
      },
      {
        "title": "U.S. FDA, Lipfendra (enlicitide) approval, 2026",
        "url": "https://www.fda.gov/news-events/press-announcements/fda-approves-first-oral-pcsk9-inhibitor-lower-ldl-cholesterol-adults-high-cholesterol",
        "supports": "补充完整骨架或临床证据"
      }
    ]
  },
  "SAR": {
    "reviewStatus": "complete",
    "naturalParent": "甘氨酸（CCD GLY）",
    "naturalParentCcd": "GLY",
    "relationship": "CCD明确把SAR关联到GLY母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C（C连接到N）",
    "changedPosition": "新增基团连接到母体的氮原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C（C连接到N）。相对天然母体：精确分子量+14.016 Da，氢键供体0，氢键受体0，拓扑极性表面积-13.99 Å²，计算脂水分配系数+0.261。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积-13.99 Å²。",
      "计算趋势：脂水分配系数+0.261、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "骨架氢键供体与暴露极性 ↓；抗蛋白酶能力 ↑；若形成紧凑转角，被动渗透性可能 ↑；本身不会明显增加疏水性。可能增加 cis/trans 构象异质性。",
      "measurement": "Sar 位于环孢素 A 的第 3 位并参与 Sar–MeLeu 的 II′ 型 β-turn。环孢素的人体口服吸收证明该单元可存在于成功口服骨架中；更适合作为转角扫描残基，而不是被视为独立的增渗基团。",
      "attributionBoundary": "证据属于完整肽、天然产物、临床骨架或专利实例；只能说明该残基与该骨架相容，不能把整分子的性质归因于一个残基。",
      "confidence": "完整肽支持"
    },
    "sources": [
      {
        "title": "RCSB CCD SAR · SARCOSINE",
        "url": "https://www.rcsb.org/ligand/SAR",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD GLY · 天然母体",
        "url": "https://www.rcsb.org/ligand/GLY",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Loosli et al., Helvetica Chimica Acta, 1985",
        "url": "https://doi.org/10.1002/hlca.19850680319",
        "supports": "提供完整肽或骨架层面的使用证据"
      },
      {
        "title": "Gupta & Benet, Biopharmaceutics & Drug Disposition, 1989",
        "url": "https://pubmed.ncbi.nlm.nih.gov/2611359/",
        "supports": "补充完整骨架或临床证据"
      }
    ]
  },
  "A1CHA": {
    "reviewStatus": "complete",
    "naturalParent": "苯丙氨酸（CCD PHE）",
    "naturalParentCcd": "PHE",
    "relationship": "CCD明确把A1CHA关联到PHE母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C、1个N（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C、1个N（C连接到C）。相对天然母体：精确分子量+29.027 Da，氢键供体+1，氢键受体+1，拓扑极性表面积+26.02 Å²，计算脂水分配系数-0.541。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体+1、氢键受体+1、极性表面积+26.02 Å²。",
      "计算趋势：脂水分配系数-0.541、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "芳香侧链维持疏水结合；额外氨甲基提供侧链交联或酰化把手；形成内酰胺或其他桥连后，构象刚性与抗酶解性可 ↑。",
      "measurement": "该二氨基酸是 enlicitide 的非蛋白源残基之一，并参与复杂的三环连接网络。它的主要价值是把芳香结合单元与共价构象约束合并在同一残基中，而不是单纯增加脂溶性。",
      "attributionBoundary": "证据属于完整肽、天然产物、临床骨架或专利实例；只能说明该残基与该骨架相容，不能把整分子的性质归因于一个残基。",
      "confidence": "完整肽支持"
    },
    "sources": [
      {
        "title": "RCSB CCD A1CHA · 3-(aminomethyl)-L-phenylalanine",
        "url": "https://www.rcsb.org/ligand/A1CHA",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PHE · 天然母体",
        "url": "https://www.rcsb.org/ligand/PHE",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Zhao et al., Precision Chemistry, 2026",
        "url": "https://doi.org/10.1021/prechem.5c00107",
        "supports": "提供完整肽或骨架层面的使用证据"
      },
      {
        "title": "U.S. FDA, Lipfendra (enlicitide) approval, 2026",
        "url": "https://www.fda.gov/news-events/press-announcements/fda-approves-first-oral-pcsk9-inhibitor-lower-ldl-cholesterol-adults-high-cholesterol",
        "supports": "补充完整骨架或临床证据"
      }
    ]
  },
  "02K": {
    "reviewStatus": "complete",
    "naturalParent": "丙氨酸（CCD ALA）",
    "naturalParentCcd": "ALA",
    "relationship": "CCD明确把02K关联到ALA母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增4个C（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增4个C（C连接到C）。相对天然母体：精确分子量+54.047 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+1.314。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+1.314、可旋转键0、环数+1。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "保留为已确认肽中使用的Ac6c构象单元",
      "measurement": "多个PDB结构确认Ac6c进入三肽和工程化肽链。 本轮示例主要是短线性肽或蛋白类似物，未确认直接环肽使用。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 02K · 1-aminocyclohexanecarboxylic acid",
        "url": "https://www.rcsb.org/ligand/02K",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD ALA · 天然母体",
        "url": "https://www.rcsb.org/ligand/ALA",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Protein-ligand interactions: thermodynamic effects associated with increasing nonpolar surface area",
        "url": "https://pubmed.ncbi.nlm.nih.gov/22007755/",
        "supports": "短肽使用"
      },
      {
        "title": "PDB 4P9Z · pTyr-Ac6c-Asn",
        "url": "https://www.rcsb.org/structure/4P9Z",
        "supports": "结构实例"
      }
    ]
  },
  "05N": {
    "reviewStatus": "complete",
    "naturalParent": "脯氨酸（CCD PRO）",
    "naturalParentCcd": "PRO",
    "relationship": "CCD明确把05N关联到PRO母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C、1个O（C连接到C；O连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C、1个O（C连接到C；O连接到C）。相对天然母体：精确分子量+30.011 Da，氢键供体+1，氢键受体+1，拓扑极性表面积+20.23 Å²，计算脂水分配系数-0.783。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体+1、氢键受体+1、极性表面积+20.23 Å²。",
      "计算趋势：脂水分配系数-0.783、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "保留为硫肽天然产物中的直接宏环残基",
      "measurement": "PDB 4G5G与5JBQ确认该残基存在于thiomuracin及其类似物；这证明宏环使用，不等同于通用SPPS单体可得。 Thiomuracin属于硫肽类宏环天然产物。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 05N · (3R,4R)-4-hydroxy-3-methyl-L-proline",
        "url": "https://www.rcsb.org/ligand/05N",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PRO · 天然母体",
        "url": "https://www.rcsb.org/ligand/PRO",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 4G5G · thiomuracin A",
        "url": "https://www.rcsb.org/structure/4G5G",
        "supports": "宏环天然产物"
      },
      {
        "title": "Antibiotic optimization and chemical structure stabilization of thiomuracin A",
        "url": "https://pubmed.ncbi.nlm.nih.gov/22812377/",
        "supports": "合成与结构优化"
      }
    ]
  },
  "0AF": {
    "reviewStatus": "complete",
    "naturalParent": "色氨酸（CCD TRP）",
    "naturalParentCcd": "TRP",
    "relationship": "CCD明确把0AF关联到TRP母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个O（O连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个O（O连接到C）。相对天然母体：精确分子量+15.995 Da，氢键供体+1，氢键受体+1，拓扑极性表面积+20.23 Å²，计算脂水分配系数-0.294。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体+1、氢键受体+1、极性表面积+20.23 Å²。",
      "计算趋势：脂水分配系数-0.294、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "该非天然构件用于扩展肽的侧链、骨架或环化化学空间；对构象、稳定性和渗透性的实际影响取决于序列与位置。",
      "measurement": "PDB 43CP在单环daropeptide天然产物中记录CCD 0AF；该结构证明确有使用，但不单独证明口服、增渗或商业可得性。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 0AF · 7-hydroxy-L-tryptophan",
        "url": "https://www.rcsb.org/ligand/0AF",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TRP · 天然母体",
        "url": "https://www.rcsb.org/ligand/TRP",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 43CP · 单环daropeptide天然产物",
        "url": "https://www.rcsb.org/structure/43CP",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "0BN": {
    "reviewStatus": "complete",
    "naturalParent": "苯丙氨酸（CCD PHE）",
    "naturalParentCcd": "PHE",
    "relationship": "CCD明确把0BN关联到PHE母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C、1个H、2个N（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C、1个H、2个N（C连接到C）。相对天然母体：精确分子量+42.022 Da，氢键供体+2，氢键受体+1，拓扑极性表面积+49.87 Å²，计算脂水分配系数-0.716。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体+2、氢键受体+1、极性表面积+49.87 Å²。",
      "计算趋势：脂水分配系数-0.716、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "该非天然构件用于扩展肽的侧链、骨架或环化化学空间；对构象、稳定性和渗透性的实际影响取决于序列与位置。",
      "measurement": "PDB 7KME在凝血酶肽样抑制剂中记录CCD 0BN；该结构证明确有使用，但不单独证明口服、增渗或商业可得性。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 0BN · 4-carbamimidoyl-L-phenylalanine",
        "url": "https://www.rcsb.org/ligand/0BN",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PHE · 天然母体",
        "url": "https://www.rcsb.org/ligand/PHE",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 7KME · 凝血酶肽样抑制剂",
        "url": "https://www.rcsb.org/structure/7KME",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "0FL": {
    "reviewStatus": "complete",
    "naturalParent": "丙氨酸（CCD ALA）",
    "naturalParentCcd": "ALA",
    "relationship": "CCD明确把0FL关联到ALA母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C、1个N、1个O（C连接到N；N连接到C）",
    "changedPosition": "新增基团连接到母体的氮原子、碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C、1个N、1个O（C连接到N；N连接到C）。相对天然母体：精确分子量+43.006 Da，氢键供体+1，氢键受体+1，拓扑极性表面积+29.1 Å²，计算脂水分配系数-1.274。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体+1、氢键受体+1、极性表面积+29.1 Å²。",
      "计算趋势：脂水分配系数-1.274、可旋转键+3、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "该非天然构件用于扩展肽的侧链、骨架或环化化学空间；对构象、稳定性和渗透性的实际影响取决于序列与位置。",
      "measurement": "PDB 1TMB在宏环肽cyclotheonamide A中记录CCD 0FL；该结构证明确有使用，但不单独证明口服、增渗或商业可得性。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 0FL · 3-amino-N-formyl-L-alanine",
        "url": "https://www.rcsb.org/ligand/0FL",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD ALA · 天然母体",
        "url": "https://www.rcsb.org/ligand/ALA",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 1TMB · 宏环肽cyclotheonamide A",
        "url": "https://www.rcsb.org/structure/1TMB",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "0LF": {
    "reviewStatus": "complete",
    "naturalParent": "脯氨酸（CCD PRO）",
    "naturalParentCcd": "PRO",
    "relationship": "CCD明确把0LF关联到PRO母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增10个C、1个O（O连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增10个C、1个O（O连接到C）。相对天然母体：精确分子量+148.089 Da，氢键供体0，氢键受体+1，拓扑极性表面积+9.23 Å²，计算脂水分配系数+2.018。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积+9.23 Å²。",
      "计算趋势：脂水分配系数+2.018、可旋转键+6、环数+1。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "该非天然构件用于扩展肽的侧链、骨架或环化化学空间；对构象、稳定性和渗透性的实际影响取决于序列与位置。",
      "measurement": "PDB 4DFW在PLK1结合肽中记录CCD 0LF；该结构证明确有使用，但不单独证明口服、增渗或商业可得性。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 0LF · (4R)-4-(4-phenylbutoxy)-L-proline",
        "url": "https://www.rcsb.org/ligand/0LF",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PRO · 天然母体",
        "url": "https://www.rcsb.org/ligand/PRO",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 4DFW · PLK1结合肽",
        "url": "https://www.rcsb.org/structure/4DFW",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "0TD": {
    "reviewStatus": "complete",
    "naturalParent": "天冬氨酸（CCD ASP）",
    "naturalParentCcd": "ASP",
    "relationship": "CCD明确把0TD关联到ASP母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C、1个S（S连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C、1个S（S连接到C）。相对天然母体：精确分子量+45.988 Da，氢键供体0，氢键受体+1，拓扑极性表面积0 Å²，计算脂水分配系数+0.341。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.341、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 10PX记录CCD 0TD；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 0TD · (3S)-3-(methylsulfanyl)-L-aspartic acid",
        "url": "https://www.rcsb.org/ligand/0TD",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD ASP · 天然母体",
        "url": "https://www.rcsb.org/ligand/ASP",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 10PX · CCD 0TD",
        "url": "https://www.rcsb.org/structure/10PX",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "0WZ": {
    "reviewStatus": "complete",
    "naturalParent": "酪氨酸（CCD TYR）",
    "naturalParentCcd": "TYR",
    "relationship": "CCD明确把0WZ关联到TYR母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增3个C、2个N（N连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增3个C、2个N（N连接到C）。相对天然母体：精确分子量+66.022 Da，氢键供体0，氢键受体+2，拓扑极性表面积+17.82 Å²，计算脂水分配系数+0.186。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+2、极性表面积+17.82 Å²。",
      "计算趋势：脂水分配系数+0.186、可旋转键+1、环数+1。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 4GES记录CCD 0WZ；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 0WZ · 3-(1H-pyrazol-1-yl)-L-tyrosine",
        "url": "https://www.rcsb.org/ligand/0WZ",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TYR · 天然母体",
        "url": "https://www.rcsb.org/ligand/TYR",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 4GES · CCD 0WZ",
        "url": "https://www.rcsb.org/structure/4GES",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "11Q": {
    "reviewStatus": "complete",
    "naturalParent": "脯氨酸（CCD PRO）",
    "naturalParentCcd": "PRO",
    "relationship": "CCD明确把11Q关联到PRO母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增7个C（C连接到N）",
    "changedPosition": "新增基团连接到母体的氮原子",
    "structuralChange": "天然母体完整保留；检测到新增7个C（C连接到N）。相对天然母体：精确分子量+96.094 Da，氢键供体-1，氢键受体0，拓扑极性表面积-8.79 Å²，计算脂水分配系数+2.293。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体-1、氢键受体0、极性表面积-8.79 Å²。",
      "计算趋势：脂水分配系数+2.293、可旋转键+2、环数+1。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "保留为Plk1环状peptomer中的直接N-取代脯氨酸构件",
      "measurement": "PDB 4HAB确认其进入PL-49。 PL-49属于直接报道的环状peptomer抑制剂。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 11Q · 1-(cyclohexylmethyl)-L-proline",
        "url": "https://www.rcsb.org/ligand/11Q",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PRO · 天然母体",
        "url": "https://www.rcsb.org/ligand/PRO",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 4HAB · Plk1-PL-49",
        "url": "https://www.rcsb.org/structure/4HAB",
        "supports": "环状peptomer结构"
      },
      {
        "title": "Development of cyclic peptomer inhibitors targeting the polo-box domain",
        "url": "https://pubmed.ncbi.nlm.nih.gov/23498919/",
        "supports": "合成与环肽使用"
      }
    ]
  },
  "1AC": {
    "reviewStatus": "complete",
    "naturalParent": "丙氨酸（CCD ALA）",
    "naturalParentCcd": "ALA",
    "relationship": "CCD明确把1AC关联到ALA母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C（C连接到C）。相对天然母体：精确分子量+12 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.144。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.144、可旋转键0、环数+1。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "保留为已确认短肽使用的Ac3c构象单元",
      "measurement": "多个PDB结构确认其进入8肽、p53肽模拟物和三肽。 本轮未确认直接环肽使用。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 1AC · 1-AMINOCYCLOPROPANECARBOXYLIC ACID",
        "url": "https://www.rcsb.org/ligand/1AC",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD ALA · 天然母体",
        "url": "https://www.rcsb.org/ligand/ALA",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 2GV2 · p53八肽类似物",
        "url": "https://www.rcsb.org/structure/2GV2",
        "supports": "短肽结构"
      },
      {
        "title": "Crystallographic Analysis of an 8-mer p53 Peptide Analogue",
        "url": "https://pubmed.ncbi.nlm.nih.gov/16925398/",
        "supports": "原始论文"
      }
    ]
  },
  "1OP": {
    "reviewStatus": "complete",
    "naturalParent": "酪氨酸（CCD TYR）",
    "naturalParentCcd": "TYR",
    "relationship": "CCD明确把1OP关联到TYR母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增5个C、1个O（C连接到O）",
    "changedPosition": "新增基团连接到母体的氧原子",
    "structuralChange": "天然母体完整保留；检测到新增5个C、1个O（C连接到O）。相对天然母体：精确分子量+86.073 Da，氢键供体0，氢键受体+1，拓扑极性表面积+9.23 Å²，计算脂水分配系数+0.836。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积+9.23 Å²。",
      "计算趋势：脂水分配系数+0.836、可旋转键+6、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "该非天然构件用于扩展肽的侧链、骨架或环化化学空间；对构象、稳定性和渗透性的实际影响取决于序列与位置。",
      "measurement": "PDB 4K0A在HIV gp120结合微型蛋白中记录CCD 1OP；该结构证明确有使用，但不单独证明口服、增渗或商业可得性。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 1OP · O-(5-hydroxypentyl)-L-tyrosine",
        "url": "https://www.rcsb.org/ligand/1OP",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TYR · 天然母体",
        "url": "https://www.rcsb.org/ligand/TYR",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 4K0A · HIV gp120结合微型蛋白",
        "url": "https://www.rcsb.org/structure/4K0A",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "1PA": {
    "reviewStatus": "complete",
    "naturalParent": "苯丙氨酸（CCD PHE）",
    "naturalParentCcd": "PHE",
    "relationship": "CCD明确把1PA关联到PHE母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增2个C、2个O（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增2个C、2个O（C连接到C）。相对天然母体：精确分子量+58.005 Da，氢键供体+1，氢键受体+1，拓扑极性表面积+37.3 Å²，计算脂水分配系数-0.373。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体+1、氢键受体+1、极性表面积+37.3 Å²。",
      "计算趋势：脂水分配系数-0.373、可旋转键+2、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "该非天然构件用于扩展肽的侧链、骨架或环化化学空间；对构象、稳定性和渗透性的实际影响取决于序列与位置。",
      "measurement": "PDB 1BHF在Lck SH2结构域肽抑制剂中记录CCD 1PA；该结构证明确有使用，但不单独证明口服、增渗或商业可得性。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 1PA · 4-(carboxymethyl)-L-phenylalanine",
        "url": "https://www.rcsb.org/ligand/1PA",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PHE · 天然母体",
        "url": "https://www.rcsb.org/ligand/PHE",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 1BHF · Lck SH2结构域肽抑制剂",
        "url": "https://www.rcsb.org/structure/1BHF",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "23P": {
    "reviewStatus": "complete",
    "naturalParent": "丙氨酸（CCD ALA）",
    "naturalParentCcd": "ALA",
    "relationship": "CCD明确把23P关联到ALA母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增3个C、1个N、1个O（N连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增3个C、1个N、1个O（N连接到C）。相对天然母体：精确分子量+71.037 Da，氢键供体+1，氢键受体+1，拓扑极性表面积+29.1 Å²，计算脂水分配系数-0.494。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体+1、氢键受体+1、极性表面积+29.1 Å²。",
      "计算趋势：脂水分配系数-0.494、可旋转键+3、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "该非天然构件用于扩展肽的侧链、骨架或环化化学空间；对构象、稳定性和渗透性的实际影响取决于序列与位置。",
      "measurement": "PDB 4I7C在Siah1结合合成肽中记录CCD 23P；该结构证明确有使用，但不单独证明口服、增渗或商业可得性。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 23P · 3-(propanoylamino)-L-alanine",
        "url": "https://www.rcsb.org/ligand/23P",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD ALA · 天然母体",
        "url": "https://www.rcsb.org/ligand/ALA",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 4I7C · Siah1结合合成肽",
        "url": "https://www.rcsb.org/structure/4I7C",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "2AG": {
    "reviewStatus": "complete",
    "naturalParent": "丙氨酸（CCD ALA）",
    "naturalParentCcd": "ALA",
    "relationship": "CCD明确把2AG关联到ALA母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增2个C（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增2个C（C连接到C）。相对天然母体：精确分子量+26.016 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.556。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.556、可旋转键+2、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "该非天然构件用于扩展肽的侧链、骨架或环化化学空间；对构象、稳定性和渗透性的实际影响取决于序列与位置。",
      "measurement": "PDB 6VY8在SFTI-1来源三唑桥环肽中记录CCD 2AG；该结构证明确有使用，但不单独证明口服、增渗或商业可得性。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 2AG · (2S)-2-aminopent-4-enoic acid",
        "url": "https://www.rcsb.org/ligand/2AG",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD ALA · 天然母体",
        "url": "https://www.rcsb.org/ligand/ALA",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 6VY8 · SFTI-1来源三唑桥环肽",
        "url": "https://www.rcsb.org/structure/6VY8",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "2GX": {
    "reviewStatus": "complete",
    "naturalParent": "苯丙氨酸（CCD PHE）",
    "naturalParentCcd": "PHE",
    "relationship": "CCD明确把2GX关联到PHE母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增6个C（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增6个C（C连接到C）。相对天然母体：精确分子量+76.031 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+1.589。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+1.589、可旋转键+1、环数+1。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "双芳基侧链显著增加疏水和芳香接触，并引入β位立体体积。",
      "measurement": "PDB 5T1K、5T1L及5U5F确认该残基进入与cetuximab Fab结合的meditope肽。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 2GX · beta-phenyl-L-phenylalanine",
        "url": "https://www.rcsb.org/ligand/2GX",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PHE · 天然母体",
        "url": "https://www.rcsb.org/ligand/PHE",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 5T1K · Meditope–cetuximab Fab",
        "url": "https://www.rcsb.org/structure/5T1K",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "2HF": {
    "reviewStatus": "complete",
    "naturalParent": "组氨酸（CCD HIS）",
    "naturalParentCcd": "HIS",
    "relationship": "CCD明确把2HF关联到HIS母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个F（F连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个F（F连接到C）。相对天然母体：精确分子量+17.991 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.139。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.139、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 3MHZ记录CCD 2HF；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 2HF · 2-fluoro-L-histidine",
        "url": "https://www.rcsb.org/ligand/2HF",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD HIS · 天然母体",
        "url": "https://www.rcsb.org/ligand/HIS",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 3MHZ · CCD 2HF",
        "url": "https://www.rcsb.org/structure/3MHZ",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "2LT": {
    "reviewStatus": "complete",
    "naturalParent": "酪氨酸（CCD TYR）",
    "naturalParentCcd": "TYR",
    "relationship": "CCD明确把2LT关联到TYR母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增2个Cl（Cl连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增2个Cl（Cl连接到C）。相对天然母体：精确分子量+67.922 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+1.307。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+1.307、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 4NXB记录CCD 2LT；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 2LT · 3,5-dichloro-L-tyrosine",
        "url": "https://www.rcsb.org/ligand/2LT",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TYR · 天然母体",
        "url": "https://www.rcsb.org/ligand/TYR",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 4NXB · CCD 2LT",
        "url": "https://www.rcsb.org/structure/4NXB",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "2ML": {
    "reviewStatus": "complete",
    "naturalParent": "亮氨酸（CCD LEU）",
    "naturalParentCcd": "LEU",
    "relationship": "CCD明确把2ML关联到LEU母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C（C连接到C）。相对天然母体：精确分子量+14.016 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.39。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.39、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "α位甲基限制主链二面角，并增加亮氨酸位点的疏水体积。",
      "measurement": "PDB 2RM9在肽类CRF受体拮抗剂Astressin2B中记录CCD 2ML。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 2ML · 2-METHYLLEUCINE",
        "url": "https://www.rcsb.org/ligand/2ML",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD LEU · 天然母体",
        "url": "https://www.rcsb.org/ligand/LEU",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 2RM9 · Astressin2B",
        "url": "https://www.rcsb.org/structure/2RM9",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "2QZ": {
    "reviewStatus": "complete",
    "naturalParent": "苏氨酸（CCD THR）",
    "naturalParentCcd": "THR",
    "relationship": "CCD明确把2QZ关联到THR母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增2个C（C连接到N）",
    "changedPosition": "新增基团连接到母体的氮原子",
    "structuralChange": "天然母体完整保留；检测到新增2个C（C连接到N）。相对天然母体：精确分子量+28.031 Da，氢键供体-1，氢键受体0，拓扑极性表面积-22.78 Å²，计算脂水分配系数+0.603。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体-1、氢键受体0、极性表面积-22.78 Å²。",
      "计算趋势：脂水分配系数+0.603、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "双甲基取代完全屏蔽骨架氮供体，并改变β支化残基的局部构象。",
      "measurement": "PDB 4V9R、4V9S和4WQU确认CCD 2QZ进入dityromycin/GE82832。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 2QZ · N,N-dimethyl-L-threonine",
        "url": "https://www.rcsb.org/ligand/2QZ",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD THR · 天然母体",
        "url": "https://www.rcsb.org/ligand/THR",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 4V9R · Dityromycin–70S ribosome",
        "url": "https://www.rcsb.org/structure/4V9R",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "2R3": {
    "reviewStatus": "complete",
    "naturalParent": "酪氨酸（CCD TYR）",
    "naturalParentCcd": "TYR",
    "relationship": "CCD明确把2R3关联到TYR母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C、1个O（C连接到O；O连接到C）",
    "changedPosition": "新增基团连接到母体的氧原子、碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C、1个O（C连接到O；O连接到C）。相对天然母体：精确分子量+30.011 Da，氢键供体0，氢键受体+1，拓扑极性表面积+9.23 Å²，计算脂水分配系数-0.206。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积+9.23 Å²。",
      "计算趋势：脂水分配系数-0.206、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "β羟基限制芳香侧链取向，O-甲基化屏蔽酚羟基并增加疏水性。",
      "measurement": "PDB 4V9R、4V9S和4WQU将该CCD记录在肽类抗生素dityromycin/GE82832中。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 2R3 · (betaR)-beta-hydroxy-O-methyl-L-tyrosine",
        "url": "https://www.rcsb.org/ligand/2R3",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TYR · 天然母体",
        "url": "https://www.rcsb.org/ligand/TYR",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 4V9R · Dityromycin–70S ribosome",
        "url": "https://www.rcsb.org/structure/4V9R",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "2RA": {
    "reviewStatus": "complete",
    "naturalParent": "丙氨酸（CCD ALA）",
    "naturalParentCcd": "ALA",
    "relationship": "CCD明确把2RA关联到ALA母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个N（N连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个N（N连接到C）。相对天然母体：精确分子量+15.011 Da，氢键供体+1，氢键受体+1，拓扑极性表面积+26.02 Å²，计算脂水分配系数-1.061。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体+1、氢键受体+1、极性表面积+26.02 Å²。",
      "计算趋势：脂水分配系数-1.061、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "短侧链伯胺可用于成环、偶联或带电相互作用，D构型同时改变局部折叠。",
      "measurement": "PDB 10SB的PCSK9环肽21及PDB 4MQ9的环七肽GE23077均包含该CCD，支持其在环状体系中的实际使用。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 2RA · 3-amino-D-alanine",
        "url": "https://www.rcsb.org/ligand/2RA",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD ALA · 天然母体",
        "url": "https://www.rcsb.org/ligand/ALA",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 10SB · PCSK9 cyclic peptide 21",
        "url": "https://www.rcsb.org/structure/10SB",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "33W": {
    "reviewStatus": "complete",
    "naturalParent": "丙氨酸（CCD ALA）",
    "naturalParentCcd": "ALA",
    "relationship": "CCD明确把33W关联到ALA母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个Br、4个C、1个S（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个Br、4个C、1个S（C连接到C）。相对天然母体：精确分子量+159.898 Da，氢键供体0，氢键受体+1，拓扑极性表面积0 Å²，计算脂水分配系数+2.047。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+2.047、可旋转键+2、环数+1。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 9JQB记录CCD 33W；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 33W · 3-(5-bromothiophen-2-yl)-L-alanine",
        "url": "https://www.rcsb.org/ligand/33W",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD ALA · 天然母体",
        "url": "https://www.rcsb.org/ligand/ALA",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 9JQB · CCD 33W",
        "url": "https://www.rcsb.org/structure/9JQB",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "3BY": {
    "reviewStatus": "complete",
    "naturalParent": "脯氨酸（CCD PRO）",
    "naturalParentCcd": "PRO",
    "relationship": "CCD明确把3BY关联到PRO母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C（C连接到N）",
    "changedPosition": "新增基团连接到母体的氮原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C（C连接到N）。相对天然母体：精确分子量+14.016 Da，氢键供体-1，氢键受体0，拓扑极性表面积-8.79 Å²，计算脂水分配系数+0.342。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体-1、氢键受体0、极性表面积-8.79 Å²。",
      "计算趋势：脂水分配系数+0.342、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "该非天然构件用于扩展肽的侧链、骨架或环化化学空间；对构象、稳定性和渗透性的实际影响取决于序列与位置。",
      "measurement": "PDB 5E2B在N端甲基化PPKRIA肽中记录CCD 3BY；该结构证明确有使用，但不单独证明口服、增渗或商业可得性。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 3BY · 1-methyl-L-proline",
        "url": "https://www.rcsb.org/ligand/3BY",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PRO · 天然母体",
        "url": "https://www.rcsb.org/ligand/PRO",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 5E2B · N端甲基化PPKRIA肽",
        "url": "https://www.rcsb.org/structure/5E2B",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "3CF": {
    "reviewStatus": "complete",
    "naturalParent": "苯丙氨酸（CCD PHE）",
    "naturalParentCcd": "PHE",
    "relationship": "CCD明确把3CF关联到PHE母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C、1个N（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C、1个N（C连接到C）。相对天然母体：精确分子量+24.995 Da，氢键供体0，氢键受体+1，拓扑极性表面积+23.79 Å²，计算脂水分配系数-0.128。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积+23.79 Å²。",
      "计算趋势：脂水分配系数-0.128、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 3OQZ记录CCD 3CF；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 3CF · 3-cyano-L-phenylalanine",
        "url": "https://www.rcsb.org/ligand/3CF",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PHE · 天然母体",
        "url": "https://www.rcsb.org/ligand/PHE",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 3OQZ · CCD 3CF",
        "url": "https://www.rcsb.org/structure/3OQZ",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "3CT": {
    "reviewStatus": "complete",
    "naturalParent": "酪氨酸（CCD TYR）",
    "naturalParentCcd": "TYR",
    "relationship": "CCD明确把3CT关联到TYR母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个Cl（Cl连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个Cl（Cl连接到C）。相对天然母体：精确分子量+33.961 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.653。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.653、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认作为非天然残基进入肽链；对构象、稳定性和渗透性的影响仍取决于具体序列与位置。",
      "measurement": "PDB 9FQB记录CCD 3CT；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 3CT · 3-chloro-L-tyrosine",
        "url": "https://www.rcsb.org/ligand/3CT",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TYR · 天然母体",
        "url": "https://www.rcsb.org/ligand/TYR",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 9FQB · CCD 3CT",
        "url": "https://www.rcsb.org/structure/9FQB",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "3GL": {
    "reviewStatus": "complete",
    "naturalParent": "谷氨酸（CCD GLU）",
    "naturalParentCcd": "GLU",
    "relationship": "CCD明确把3GL关联到GLU母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个O（O连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个O（O连接到C）。相对天然母体：精确分子量+15.995 Da，氢键供体+1，氢键受体+1，拓扑极性表面积+20.23 Å²，计算脂水分配系数-1.029。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体+1、氢键受体+1、极性表面积+20.23 Å²。",
      "计算趋势：脂水分配系数-1.029、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "额外羟基和羧基形成高极性、定向氢键丰富的受限残基。",
      "measurement": "PDB 2MC0在环状硫肽抗生素nosiheptide中记录CCD 3GL。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 3GL · (2S,4S)-2-amino-4-hydroxy-pentanedioic acid",
        "url": "https://www.rcsb.org/ligand/3GL",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD GLU · 天然母体",
        "url": "https://www.rcsb.org/ligand/GLU",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 2MC0 · Nosiheptide–TipAS complex",
        "url": "https://www.rcsb.org/structure/2MC0",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "3MY": {
    "reviewStatus": "complete",
    "naturalParent": "酪氨酸（CCD TYR）",
    "naturalParentCcd": "TYR",
    "relationship": "CCD明确把3MY关联到TYR母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个Cl（Cl连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个Cl（Cl连接到C）。相对天然母体：精确分子量+33.961 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.653。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.653、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "D型芳香酚与邻位氯代共同调节电子性质、疏水接触和交联构象。",
      "measurement": "PDB 2XAD及3MG9确认该残基处于teicoplanin交联糖肽骨架；属于复杂天然产物构件。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 3MY · 3-chloro-D-tyrosine",
        "url": "https://www.rcsb.org/ligand/3MY",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TYR · 天然母体",
        "url": "https://www.rcsb.org/ligand/TYR",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 2XAD · Teicoplanin complex",
        "url": "https://www.rcsb.org/structure/2XAD",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "3PX": {
    "reviewStatus": "complete",
    "naturalParent": "脯氨酸（CCD PRO）",
    "naturalParentCcd": "PRO",
    "relationship": "CCD明确把3PX关联到PRO母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增3个C、1个O（O连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增3个C、1个O（O连接到C）。相对天然母体：精确分子量+58.042 Da，氢键供体0，氢键受体+1，拓扑极性表面积+9.23 Å²，计算脂水分配系数+0.403。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积+9.23 Å²。",
      "计算趋势：脂水分配系数+0.403、可旋转键+2、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "脯氨酸环与异丙氧基共同限制转角，并增加局部疏水表面。",
      "measurement": "PDB 3RJM在caspase-2底物型肽抑制剂中记录CCD 3PX。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 3PX · (3S)-3-(propan-2-yloxy)-L-proline",
        "url": "https://www.rcsb.org/ligand/3PX",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PRO · 天然母体",
        "url": "https://www.rcsb.org/ligand/PRO",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 3RJM · Caspase-2 peptide inhibitor",
        "url": "https://www.rcsb.org/structure/3RJM",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "3YM": {
    "reviewStatus": "complete",
    "naturalParent": "酪氨酸（CCD TYR）",
    "naturalParentCcd": "TYR",
    "relationship": "CCD明确把3YM关联到TYR母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C、1个O（O连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C、1个O（O连接到C）。相对天然母体：精确分子量+30.011 Da，氢键供体0，氢键受体+1，拓扑极性表面积+9.23 Å²，计算脂水分配系数+0.009。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积+9.23 Å²。",
      "计算趋势：脂水分配系数+0.009、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 6OFN记录CCD 3YM；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 3YM · 3-methoxy-L-tyrosine",
        "url": "https://www.rcsb.org/ligand/3YM",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TYR · 天然母体",
        "url": "https://www.rcsb.org/ligand/TYR",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 6OFN · CCD 3YM",
        "url": "https://www.rcsb.org/structure/6OFN",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "41H": {
    "reviewStatus": "complete",
    "naturalParent": "苯丙氨酸（CCD PHE）",
    "naturalParentCcd": "PHE",
    "relationship": "CCD明确把41H关联到PHE母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C（C连接到C）。相对天然母体：精确分子量+14.016 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.561。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.561、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "β位甲基增加芳香侧链的立体约束，可改变局部构象和疏水接触。",
      "measurement": "PDB 4XC1在HIV gp41表位肽中记录CCD 41H。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 41H · (betaS)-beta-methyl-L-phenylalanine",
        "url": "https://www.rcsb.org/ligand/41H",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PHE · 天然母体",
        "url": "https://www.rcsb.org/ligand/PHE",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 4XC1 · HIV gp41 peptide epitope",
        "url": "https://www.rcsb.org/structure/4XC1",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "4AF": {
    "reviewStatus": "complete",
    "naturalParent": "苯丙氨酸（CCD PHE）",
    "naturalParentCcd": "PHE",
    "relationship": "CCD明确把4AF关联到PHE母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增2个C、1个O（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增2个C、1个O（C连接到C）。相对天然母体：精确分子量+42.011 Da，氢键供体0，氢键受体+1，拓扑极性表面积+17.07 Å²，计算脂水分配系数+0.203。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积+17.07 Å²。",
      "计算趋势：脂水分配系数+0.203、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 3HWL记录CCD 4AF；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 4AF · 4-ACETYL-L-PHENYLALANINE",
        "url": "https://www.rcsb.org/ligand/4AF",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PHE · 天然母体",
        "url": "https://www.rcsb.org/ligand/PHE",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 3HWL · CCD 4AF",
        "url": "https://www.rcsb.org/structure/3HWL",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "4CF": {
    "reviewStatus": "complete",
    "naturalParent": "苯丙氨酸（CCD PHE）",
    "naturalParentCcd": "PHE",
    "relationship": "CCD明确把4CF关联到PHE母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个C、1个N（C连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个C、1个N（C连接到C）。相对天然母体：精确分子量+24.995 Da，氢键供体0，氢键受体+1，拓扑极性表面积+23.79 Å²，计算脂水分配系数-0.128。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积+23.79 Å²。",
      "计算趋势：脂水分配系数-0.128、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 3OQY记录CCD 4CF；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 4CF · 4-cyano-L-phenylalanine",
        "url": "https://www.rcsb.org/ligand/4CF",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PHE · 天然母体",
        "url": "https://www.rcsb.org/ligand/PHE",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 3OQY · CCD 4CF",
        "url": "https://www.rcsb.org/structure/3OQY",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "4CY": {
    "reviewStatus": "complete",
    "naturalParent": "甲硫氨酸（CCD MET）",
    "naturalParentCcd": "MET",
    "relationship": "CCD明确把4CY关联到MET母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个N（N连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个N（N连接到C）。相对天然母体：精确分子量+10.98 Da，氢键供体0，氢键受体+1，拓扑极性表面积+23.79 Å²，计算脂水分配系数-0.149。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积+23.79 Å²。",
      "计算趋势：脂水分配系数-0.149、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 3OR0记录CCD 4CY；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 4CY · nitrilo-L-methionine",
        "url": "https://www.rcsb.org/ligand/4CY",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD MET · 天然母体",
        "url": "https://www.rcsb.org/ligand/MET",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 3OR0 · CCD 4CY",
        "url": "https://www.rcsb.org/structure/3OR0",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "4FB": {
    "reviewStatus": "complete",
    "naturalParent": "脯氨酸（CCD PRO）",
    "naturalParentCcd": "PRO",
    "relationship": "CCD明确把4FB关联到PRO母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个F（F连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个F（F连接到C）。相对天然母体：精确分子量+17.991 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数-0.052。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数-0.052、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "主链氢键供体缺失；构象刚性与特定脯氨酸环折叠倾向 ↑；可微调 cis/trans 平衡、代谢稳定性和交联几何；疏水性只轻度改变。",
      "measurement": "PCSK9 环肽专利在化合物 102 的固相合成中明确使用 (2S,4S)-4-fluoroproline，说明它是实际制备过的骨架构件，而不是只存在于宽泛通式中。专利未提供该残基与 Pro 的单点渗透性对照。",
      "attributionBoundary": "证据属于完整肽、天然产物、临床骨架或专利实例；只能说明该残基与该骨架相容，不能把整分子的性质归因于一个残基。",
      "confidence": "完整肽支持"
    },
    "sources": [
      {
        "title": "RCSB CCD 4FB · (4S)-4-FLUORO-L-PROLINE",
        "url": "https://www.rcsb.org/ligand/4FB",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PRO · 天然母体",
        "url": "https://www.rcsb.org/ligand/PRO",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "WO2019246405A1, Merck / Ra Pharmaceuticals, 2019",
        "url": "https://patents.google.com/patent/WO2019246405A1/en",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "4FW": {
    "reviewStatus": "complete",
    "naturalParent": "色氨酸（CCD TRP）",
    "naturalParentCcd": "TRP",
    "relationship": "CCD明确把4FW关联到TRP母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个F（F连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个F（F连接到C）。相对天然母体：精确分子量+17.991 Da，氢键供体0，氢键受体0，拓扑极性表面积0 Å²，计算脂水分配系数+0.139。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体0、极性表面积0 Å²。",
      "计算趋势：脂水分配系数+0.139、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 1RM9记录CCD 4FW；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 4FW · 4-FLUOROTRYPTOPHANE",
        "url": "https://www.rcsb.org/ligand/4FW",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TRP · 天然母体",
        "url": "https://www.rcsb.org/ligand/TRP",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 1RM9 · CCD 4FW",
        "url": "https://www.rcsb.org/structure/1RM9",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "4II": {
    "reviewStatus": "complete",
    "naturalParent": "苯丙氨酸（CCD PHE）",
    "naturalParentCcd": "PHE",
    "relationship": "CCD明确把4II关联到PHE母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增3个N（N连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增3个N（N连接到C）。相对天然母体：精确分子量+41.001 Da，氢键供体0，氢键受体+1，拓扑极性表面积+48.76 Å²，计算脂水分配系数+0.942。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体0、氢键受体+1、极性表面积+48.76 Å²。",
      "计算趋势：脂水分配系数+0.942、可旋转键+1、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "对位叠氮基提供光交联或点击化学位点；实验过程中也可能发生部分还原。",
      "measurement": "pAzF 与 AlkynK 被共同编码进多种大环肽并由质谱确认；原文特别报告部分叠氮基会还原为胺，使用时需检查最终化学状态。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 4II · (2~{S})-2-azanyl-3-(4-azidophenyl)propanoic acid",
        "url": "https://www.rcsb.org/ligand/4II",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD PHE · 天然母体",
        "url": "https://www.rcsb.org/ligand/PHE",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "Spinck et al., Nature Chemistry, 2023",
        "url": "https://pubmed.ncbi.nlm.nih.gov/36550233/",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  },
  "4IN": {
    "reviewStatus": "complete",
    "naturalParent": "色氨酸（CCD TRP）",
    "naturalParentCcd": "TRP",
    "relationship": "CCD明确把4IN关联到TRP母体；原子级比对显示天然母体重原子骨架完整保留。该关系表示结构衍生，不表示工业生产必须以天然氨基酸为起始原料。",
    "changeLabel": "检测到新增1个N（N连接到C）",
    "changedPosition": "新增基团连接到母体的碳原子",
    "structuralChange": "天然母体完整保留；检测到新增1个N（N连接到C）。相对天然母体：精确分子量+15.011 Da，氢键供体+1，氢键受体+1，拓扑极性表面积+26.02 Å²，计算脂水分配系数-0.418。",
    "directlyCausedProperties": [
      "结构直接变化：氢键供体+1、氢键受体+1、极性表面积+26.02 Å²。",
      "计算趋势：脂水分配系数-0.418、可旋转键0、环数0。这些数值用于解释可能的极性、疏水性和刚性变化。",
      "尚无单残基性质对照，不能把上述计算变化直接写成渗透性、稳定性或口服吸收改善。"
    ],
    "peptideExperiment": {
      "conclusion": "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
      "measurement": "PDB 1OXF记录CCD 4IN；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。",
      "attributionBoundary": "目前没有修饰前后性质实验。这里的分子描述符变化是计算结果，不是溶解度、渗透性、稳定性或口服吸收的实测结论。",
      "confidence": "结构推断"
    },
    "sources": [
      {
        "title": "RCSB CCD 4IN · 4-AMINO-L-TRYPTOPHAN",
        "url": "https://www.rcsb.org/ligand/4IN",
        "supports": "确认衍生物名称、结构和CCD天然母体关系"
      },
      {
        "title": "RCSB CCD TRP · 天然母体",
        "url": "https://www.rcsb.org/ligand/TRP",
        "supports": "确认天然氨基酸母体结构"
      },
      {
        "title": "PDB 1OXF · CCD 4IN",
        "url": "https://www.rcsb.org/structure/1OXF",
        "supports": "提供完整肽或骨架层面的使用证据"
      }
    ]
  }
};
