export const pdbBatch8Records = [
  ["00C", "3FII", "3-磺基-D-丙氨酸", "3-sulfo-D-alanine", "肉毒毒素肽模拟抑制剂"],
  ["01W", "3DS9", "二硝基苯基鸟氨酸", "2,4-dinitrophenyl-modified ornithine", "肉毒毒素A肽模拟抑制剂"],
  ["02V", "3S04", "N-甲基二羟基苯基甘氨酸", "N-methyl-3,4-dihydroxyphenylglycine", "芳霉素脂糖肽抗生素"],
  ["03Y", "3RQD", "2-甲基-L-半胱氨酸", "2-methyl-L-cysteine", "HDAC8结合的缩肽"],
  ["04Q", "7JX5", "N-苄基甘氨酸", "N-benzylglycine", "peptoid修饰的胶原三螺旋肽"],
  ["04X", "4U1V", "吗啉甲基四氢吡啶羧酸", "morpholinylmethyl tetrahydropyridine carboxylic acid", "核糖体结合的linopristin"],
  ["08M", "3U4W", "N5-吡嗪甲酰-L-鸟氨酸", "N5-pyrazinoyl-L-ornithine", "DNA模板合成的Src宏环抑制剂"],
  ["0AF", "43CP", "7-羟基-L-色氨酸", "7-hydroxy-L-tryptophan", "单环daropeptide天然产物"],
  ["0AR", "1H0G", "N-乙酰胍基鸟氨酸", "N-acetylguanidino ornithine", "天然环五肽argadin"],
  ["0BN", "7KME", "4-胍基-L-苯丙氨酸", "4-carbamimidoyl-L-phenylalanine", "凝血酶肽样抑制剂"],
  ["0FL", "1TMB", "3-氨基-N-甲酰-L-丙氨酸", "3-amino-N-formyl-L-alanine", "宏环肽cyclotheonamide A"],
  ["0LF", "4DFW", "4-(4-苯基丁氧基)-L-脯氨酸", "4-(4-phenylbutoxy)-L-proline", "PLK1结合肽"],
  ["1E3", "4I80", "2,9-二氨基壬酸", "2,9-diaminononanoic acid", "menin宏环肽模拟物"],
  ["1IC", "7NA7", "O-辛酰-D-丝氨酸", "O-octanoyl-D-serine", "ghrelin受体肽激动剂"],
  ["1MH", "4JJ7", "3-吡啶基-L-丙氨酸", "3-pyridyl-L-alanine", "caspase-3非天然氨基酸肽"],
  ["1OP", "4K0A", "O-(5-羟戊基)-L-酪氨酸", "O-(5-hydroxypentyl)-L-tyrosine", "HIV gp120结合微型蛋白"],
  ["1PA", "1BHF", "4-羧甲基-L-苯丙氨酸", "4-(carboxymethyl)-L-phenylalanine", "Lck SH2结构域肽抑制剂"],
  ["1U8", "4JJ7", "二甲基苯甲酰氧基β-氨基酸", "dimethylbenzoyloxy beta-amino acid", "caspase-3非天然氨基酸肽"],
  ["200", "3Q4K", "4-氯-L-苯丙氨酸", "4-chloro-L-phenylalanine", "DNA滑动夹结合短肽"],
  ["23P", "4I7C", "N-丙酰基二氨基丙酸", "3-(propanoylamino)-L-alanine", "Siah1结合合成肽"],
  ["2AG", "6VY8", "L-烯丙基甘氨酸", "(2S)-2-aminopent-4-enoic acid", "SFTI-1来源三唑桥环肽"],
  ["2KK", "4NMS", "N6-(4-氟苯甲酰)-L-赖氨酸", "N6-(4-fluorobenzoyl)-L-lysine", "CAL-PDZ结合修饰肽"],
  ["2L6", "6SYJ", "螺环脯氨酸模拟物", "spirocyclic proline mimic", "胶原三螺旋肽"],
  ["2MT", "1SBU", "二甲基噻唑烷羧酸", "2,2-dimethylthiazolidine-4-carboxylic acid", "δ-conotoxin环区模拟肽"],
  ["34E", "4TOT", "哌嗪基-N-甲基缬氨酸", "piperazinyl-N-methyl-L-valine", "环孢亲和素非免疫抑制性抑制剂"],
  ["3BY", "5E2B", "1-甲基-L-脯氨酸", "1-methyl-L-proline", "N端甲基化PPKRIA肽"],
  ["4BF", "3NI3", "4-溴-L-苯丙氨酸", "4-bromo-L-phenylalanine", "54元环宏环β折叠肽"],
  ["4DB", "3JXT", "二甲氨基邻苯二甲酰基鸟氨酸", "dimethylaminophthalimide ornithine", "PDZ结构域荧光肽配体"],
  ["4DP", "2IPK", "二甲氨基邻苯二甲酰基丙氨酸", "dimethylaminophthalimide alanine", "HLA-DR1荧光肽"],
  ["4J5", "6D2U", "双氨基胍基丁酸", "bis-amino guanidinobutanoic acid", "HIV TAR RNA高亲和宏环"],
  ["4KY", "4X9V", "N-乙酰辛烯氧基脯氨酸", "N-acetyl-4-(octenyloxy)-L-proline", "PLK1结合磷酸肽宏环"],
  ["4L0", "4X9R", "N-乙酰己氧基脯氨酸", "N-acetyl-4-(hexyloxy)-L-proline", "PLK1结合磷酸肽宏环"],
  ["4OG", "9ASF", "苯并噻吩基-L-丙氨酸", "benzothienyl-L-alanine", "HLA-A*03:01结合肽"],
  ["5OM", "5EFJ", "环氧二羟基辛氨酸", "epoxy-dihydroxyoctanoic acid", "环状天然产物HC toxin"],
  ["5T3", "6V8W", "N6-乙基-N6-异丙基-L-赖氨酸", "N6-ethyl-N6-isopropyl-L-lysine", "CDYL2结合合成肽"],
  ["73C", "5EEL", "O-丁基-L-丝氨酸", "O-butyl-L-serine", "Grb7 SH2双环肽抑制剂"],
  ["7QK", "8SB6", "N6-乙酰-N6-甲基-L-赖氨酸", "N6-acetyl-N6-methyl-L-lysine", "BRD2结合组蛋白肽"],
  ["7TK", "7YUZ", "β³-高谷氨酰胺吡咯烷酰胺", "beta3 pyrrolidinamide amino acid", "KRAS环肽抑制剂AP8784"],
  ["7W2", "7YV1", "二氟三氟甲基高苯丙氨酸", "difluoro-trifluoromethyl homophenylalanine", "KRAS环肽抑制剂LUNA18"],
  ["81R", "4OS4", "(R)-二巯基正缬氨酸", "(4R)-4,5-disulfanyl-L-norvaline", "uPA双环肽UK603"],
  ["81S", "2MOA", "(S)-二巯基正缬氨酸", "(4S)-4,5-disulfanyl-L-norvaline", "环化肽ImI1"],
  ["823", "4OS7", "双巯丙基-L-天冬酰胺", "N,N-bis(3-sulfanylpropyl)-L-asparagine", "uPA双环肽UK607"],
  ["9DT", "5NX2", "2-氟-α-甲基-L-苯丙氨酸", "2-fluoro-alpha-methyl-L-phenylalanine", "GLP-1受体肽激动剂"],
  ["9E7", "5VK0", "N6-巯甲基-L-赖氨酸", "N6-(sulfanylmethyl)-L-lysine", "MDM2二硫代氨基甲酸酯订书肽"],
  ["9WV", "5W6R", "β-丙氨酰-3-氨基丙氨酸", "beta-alanyl-3-amino-L-alanine", "流感血凝素环肽CP141099"],
  ["A1A2I", "8GCG", "β²-高缬氨酸", "(2S)-2-(aminomethyl)-3-methylbutanoic acid", "MDM2肽模拟抑制剂"],
  ["A1A2K", "8GCG", "三唑羧甲基-D-丙氨酸", "triazole-carboxymethyl-D-alanine", "MDM2肽模拟抑制剂"],
  ["A1A3M", "9D9A", "脱氢氮杂脯氨酸", "dehydro-aza-proline", "禽胰多肽氮杂脯氨酸替换体"],
  ["A1ADW", "9R9M", "邻甲基苯基氨基二醇", "o-tolyl amino diol", "MLH1结合环肽"],
  ["A1AZQ", "9CS2", "N-苯乙基甘氨酸", "N-(2-phenylethyl)glycine", "BamA结合环肽CP3"],
  ["A1CCQ", "9OLA", "Nα-氨基-L-酪氨酸", "N-alpha-amino-L-tyrosine", "骨架修饰平行β发夹肽"],
  ["A1CCR", "9OL9", "Nα-氨基-L-苯丙氨酸", "N-alpha-amino-L-phenylalanine", "骨架修饰平行β发夹肽"],
  ["A1CCS", "9OL8", "Nα-氨基-L-精氨酸", "N-alpha-amino-L-arginine", "骨架修饰平行β发夹肽"],
  ["A1CRT", "9PHD", "羟基硫醚桥联氨基酸", "hydroxy thioether-bridged amino acid", "流感血凝素融合抑制环肽CP141076"],
  ["A1CTT", "9Y6C", "D-苯基甘氨酸", "D-phenylglycine", "补体C5结合肽Ra30303"],
  ["A1E3Y", "22EM", "D-β³-苯丙氨酸", "(3R)-3-amino-3-phenylpropanoic acid", "κ阿片受体β肽配体"],
  ["A1EDD", "9PKU", "N-甲磺酰-D-赖氨酸", "N-methylsulfonyl-D-lysine", "YEATS2结合肽LS-131"],
  ["A1H2H", "8RHK", "3-氟-4-硝基-L-苯丙氨酸", "3-fluoro-4-nitro-L-phenylalanine", "线性氧化吲哚环氧酮蛋白酶体抑制剂"],
  ["A1H2I", "8RHK", "(S)-羟基氧化吲哚丙氨酸", "(S)-hydroxy-oxindole alanine", "线性氧化吲哚环氧酮蛋白酶体抑制剂"],
  ["A1H45", "8RHJ", "(R)-羟基氧化吲哚丙氨酸", "(R)-hydroxy-oxindole alanine", "宏环氧化吲哚环氧酮蛋白酶体抑制剂"],
  ["A1I4F", "9QBT", "3-氯苯甲酰哌嗪羧酸", "chlorobenzoyl piperazine carboxylic acid", "KEAP1结合环肽"],
  ["A1ICB", "9FBI", "氯甲基苯甲酰氨基脯氨酸", "chloromethylbenzamido proline", "CK2环状肽模拟物"],
  ["A1ICC", "9FBL", "异喹啉甲酰氨基脯氨酸", "isoquinolinecarbonylamino proline", "CK2环状肽模拟物"],
  ["A1IM3", "9EO6", "D-β³-色氨酸醛", "D-beta3-tryptophan aldehyde", "SARS-CoV-2 Mpro共价肽样抑制剂"],
  ["A1JND", "9SAB", "三唑丁基N-取代甘氨酸", "triazolylbutyl N-substituted glycine", "14-3-3结合宏环"],
  ["A1JNL", "9SAC", "三唑丙基N-取代氨基丁酸", "triazolylpropyl N-substituted aminobutyrate", "14-3-3结合宏环"],
  ["A1JNX", "9SA9", "三唑乙基N-取代甘氨酸", "triazolylethyl N-substituted glycine", "14-3-3结合宏环"],
  ["A1JWF", "9S78", "2-碲吩基丙氨酸", "2-tellurophenealanine", "碲吩标记carfilzomib"],
  ["A1LWV", "6IQH", "N6-(5-氧代戊酰)-L-赖氨酸", "N6-(5-oxopentanoyl)-L-lysine", "与Fc共价结合的肽"],
  ["A1MFG", "24HR", "氟三氟甲基高苯丙氨酸", "fluoro-trifluoromethyl homophenylalanine", "KRAS宏环肽抑制剂AP6252"],
  ["ACA", "1ILP", "6-氨基己酸", "6-aminohexanoic acid", "CXCR1 N端肽"],
  ["AEA", "1BZH", "氨基甲酰乙基硫代甘氨酸", "carbamoylethylthio glycine", "PTP1B环肽抑制剂"],
  ["AHP", "1J4X", "2-氨基庚酸", "2-aminoheptanoic acid", "双特异性磷酸酶结合肽"],
  ["ALN", "1B0H", "2-萘基丙氨酸", "2-naphthylalanine", "寡肽结合蛋白三肽配体"],
  ["B5I", "8RU4", "2-丙基-L-正缬氨酸", "2-propyl-L-norvaline", "β-catenin stitched peptide抑制剂"],
  ["BCX", "1J8Z", "β³-高半胱氨酸", "(3R)-3-amino-4-sulfanylbutanoic acid", "HIV gp41 β³模拟肽"],
  ["BTR", "1WCT", "6-溴色氨酸", "6-bromotryptophan", "天然conotoxin"],
  ["BUC", "6CXG", "S-丁基硫代半胱氨酸", "S,S-butylthiocysteine", "抗HIV糖肽"],
  ["CCJ", "8ZCS", "羧甲基-D-半胱氨酸", "carboxymethyl-D-cysteine", "MCL1环肽抑制剂"],
  ["CCS", "3PQZ", "羧甲基-L-半胱氨酸", "carboxymethyl-L-cysteine", "Grb7 SH2结合肽"],
  ["CSA", "6TWB", "S-丙酮基-L-半胱氨酸", "S-acetonyl-L-cysteine", "凝血因子XIa双桥肽"],
  ["CSO", "3BOO", "S-羟基-L-半胱氨酸", "S-hydroxy-L-cysteine", "肉毒毒素抑制肽"],
  ["CY1", "1D5M", "乙酰氨甲基-L-半胱氨酸", "acetamidomethyl-L-cysteine", "HLA-DR4结合肽"],
  ["D8R", "8HN9", "N6-D-乳酰-L-赖氨酸", "N6-D-lactyl-L-lysine", "SIRT3识别的乳酰化肽"],
  ["DFF", "4LTE", "4-苯甲酰-D-苯丙氨酸", "4-benzoyl-D-phenylalanine", "胰岛素降解酶宏环抑制剂"],
  ["DFI", "1APW", "2,2-二氟statine", "2,2-difluorostatine", "青霉胃蛋白酶过渡态模拟肽"],
  ["DFO", "1APV", "2,2-二氟-3-hydroxystatine", "2,2-difluoro-3-hydroxystatine", "青霉胃蛋白酶过渡态模拟肽"],
  ["DNP", "1BEI", "2,3-二氨基丙酸", "2,3-diaminopropionic acid", "ShK来源免疫抑制肽"],
  ["DOA", "1EOJ", "12-氨基十二酸", "12-aminododecanoic acid", "三价凝血酶抑制肽"],
  ["ELY", "5EPJ", "N6,N6-二乙基-L-赖氨酸", "N6,N6-diethyl-L-lysine", "CBX7肽模拟抑制剂"],
  ["ESC", "1KBG", "乙硫基-L-高半胱氨酸", "2-amino-4-ethylsulfanylbutyric acid", "MHC-I呈递糖肽"],
  ["EUP", "6CAE", "4-氨基-L-别苏氨酸", "4-amino-L-allothreonine", "NOSO-95179肽类抗生素"],
  ["F2F", "3D3V", "3,4-二氟-L-苯丙氨酸", "3,4-difluoro-L-phenylalanine", "TCR识别的HLA-A2修饰肽"],
  ["F93", "6M5E", "氯羟基-D-苯基甘氨酸", "chloro-hydroxy-D-phenylglycine", "环状糖肽dalbavancin"],
  ["FAK", "4L3O", "N6-三氟乙酰-L-赖氨酸", "N6-trifluoroacetyl-L-lysine", "SIRT2宏环肽"],
  ["FL6", "7C8B", "L-谷氨酸甲酯", "L-glutamic acid methyl ester", "SARS-CoV-2 Mpro肽样抑制剂"],
  ["FOD", "6CXG", "羟基环己基三唑高丙氨酸", "hydroxycyclohexyl-triazole homoalanine", "抗HIV糖肽"],
  ["IAR", "6CAE", "脱氢精氨酸", "dehydroarginine", "NOSO-95179肽类抗生素"],
  ["IOY", "5F1W", "4-碘-D-苯丙氨酸", "4-iodo-D-phenylalanine", "α-synuclein片段来源宏环肽"],
  ["IPG", "2SEM", "N-异丙基甘氨酸", "N-isopropylglycine", "SEM5 SH3结合peptoid抑制剂"],
] as const;

export const pdbBatch8Residues = pdbBatch8Records.map(([ccd, pdb, name, english, context]) => ({
  name,
  english: `${english} · CCD ${ccd}`,
  effect: "该非天然构件用于扩展肽的侧链、骨架或环化化学空间；对构象、稳定性和渗透性的实际影响取决于序列与位置。",
  evidence: `PDB ${pdb}在${context}中记录CCD ${ccd}；该结构证明确有使用，但不单独证明口服、增渗或商业可得性。`,
  paper: `PDB ${pdb} · ${context}`,
  href: `https://www.rcsb.org/structure/${pdb}`,
  level: "实际使用证据" as const,
}));

export const pdbBatch8StructureMappings = Object.fromEntries(
  pdbBatch8Records.map(([ccd, , , english]) => [`${english} · CCD ${ccd}`, { ccd, label: english }]),
);
