export const pdbBatch9EvidenceRecords = [
  ["004", "1SM1", "奎奴普丁/达福普汀中的苯基甘氨酸样构件", "special-reference"],
  ["00E", "5CGG", "蛋白酶体抑制剂中的氯乙酰胺肽模拟构件", "special-reference"],
  ["0TD", "10PX", "核糖体结合的大环内酯特殊构件", "special-reference"],
  ["0WZ", "4GES", "遗传编码并进入GFP的吡唑基酪氨酸", "special-reference"],
  ["0XL", "4GM3", "WDR5肽模拟配体MM-101构件", "special-reference"],
  ["13E", "3URI", "内硫肽酶抑制剂的羟乙烯肽模拟构件", "special-reference"],
  ["193", "1XY5", "生长抑素类似肽中的非天然残基", "evidence-reviewed-residue"],
  ["19W", "4HU5", "交联肽中的氨氧基正缬氨酸衍生残基", "evidence-reviewed-residue"],
  ["1C3", "4HY2", "PLK1结合肽中的非天然残基", "evidence-reviewed-residue"],
  ["1QI", "7OUP", "DPP3配体中的羟乙烯肽模拟单元", "special-reference"],
  ["23F", "1VRZ", "设计型螺旋-转角-螺旋肽中的非天然残基", "evidence-reviewed-residue"],
  ["23S", "1RMP", "GFP中的遗传编码硒代色氨酸类似物", "special-reference"],
  ["2HF", "3MHZ", "长蛋白中的氟代组氨酸", "special-reference"],
  ["2L5", "5N91", "ENAH结合肽中的2-氯苯丙氨酸", "evidence-reviewed-residue"],
  ["2LT", "4NXB", "iLOV蛋白中的二氯酪氨酸", "special-reference"],
  ["2MR", "2V87", "组蛋白肽中的二甲基精氨酸", "evidence-reviewed-residue"],
  ["30F", "4Q9I", "P-糖蛋白配体中的QZ-Ala肽模拟构件", "special-reference"],
  ["32S", "1RMM", "GFP中的硒代色氨酸类似物", "special-reference"],
  ["32T", "1RMO", "GFP中的噻吩并吡咯氨基酸类似物", "special-reference"],
  ["33W", "9JQB", "铁蛋白中的溴噻吩丙氨酸", "special-reference"],
  ["3CF", "3OQZ", "半合成RNase S中的氰基苯丙氨酸", "special-reference"],
  ["3CT", "9FQB", "HNP1防御素肽中的3-氯酪氨酸", "evidence-reviewed-residue"],
  ["3YM", "6OFN", "GFP中的甲氧基酪氨酸", "special-reference"],
  ["4AF", "3HWL", "T4溶菌酶中的对乙酰苯丙氨酸", "special-reference"],
  ["4AK", "4YDM", "转甲状腺素蛋白缀合物中的修饰赖氨酸", "special-reference"],
  ["4AW", "4B2M", "dodecin蛋白中的氮杂色氨酸", "special-reference"],
  ["4CF", "3OQY", "RNase S中的氰基苯丙氨酸", "special-reference"],
  ["4CY", "3OR0", "半合成RNase S中的氰化高半胱氨酸", "special-reference"],
  ["4D4", "10QM", "核糖体配体48a中的特殊构件", "special-reference"],
  ["4FB", "5OWP", "糖肽中的4-氟脯氨酸残基", "evidence-reviewed-residue"],
  ["4FW", "1RM9", "GFP中的氟代色氨酸", "special-reference"],
  ["4IN", "1OXF", "GFP中的氨基色氨酸", "special-reference"],
  ["4L8", "4Z7I", "受体配体中的β-氨基酸样构件", "special-reference"],
  ["4LZ", "4WVS", "XIAP结合肽中的修饰酪氨酸", "evidence-reviewed-residue"],
  ["4OO", "5XHF", "曲妥珠单抗Fab中的对叠氮苯丙氨酸", "special-reference"],
  ["4OU", "4ZJ1", "β-内酰胺酶中的对丙烯酰胺苯丙氨酸", "special-reference"],
  ["4QK", "2NA5", "PYY肽缀合物中的三唑正亮氨酸", "evidence-reviewed-residue"],
  ["4V0", "5BTT", "GFP中的氮杂环庚烯丙氨酸修饰", "special-reference"],
  ["51T", "5CI2", "核糖核苷酸还原酶中的三氟酪氨酸", "special-reference"],
  ["55I", "8HOQ", "P450蛋白中的三氟甲基苯丙氨酸", "special-reference"],
  ["5CT", "5DS8", "抗体识别的hypusine蛋白修饰", "special-reference"],
  ["5DW", "5DPJ", "sfGFP中的乙炔基苯丙氨酸", "special-reference"],
  ["5F0", "7P2E", "线粒体核糖体中的谷氨酸甲酯修饰", "special-reference"],
  ["5GG", "5DUB", "抗体识别的脱氧hypusine蛋白修饰", "special-reference"],
  ["5MW", "5E6J", "泛素活性探针中的三唑赖氨酸构件", "special-reference"],
  ["5OH", "4V7C", "卷曲霉素-核糖体体系中的特殊构件", "special-reference"],
  ["5OL", "5EFN", "组蛋白三肽中的修饰赖氨酸", "evidence-reviewed-residue"],
  ["62H", "5HFY", "GB1模型肽中的β2-丙氨酸", "evidence-reviewed-residue"],
  ["6CL", "2AIZ", "肽聚糖配体中的羧基赖氨酸样构件", "special-reference"],
  ["6CV", "5IR1", "meditope肽中的3-溴苯丙氨酸", "evidence-reviewed-residue"],
  ["6DN", "5J2S", "蛋白中的羧甲基赖氨酸样修饰", "special-reference"],
  ["6DU", "5ITF", "meditope肽中的2-溴苯丙氨酸", "evidence-reviewed-residue"],
  ["6G5", "9ETH", "肽配体中的4-氯色氨酸", "evidence-reviewed-residue"],
  ["73N", "5LRG", "环状anabaenopeptin B中的氨甲酰精氨酸样残基", "evidence-reviewed-residue"],
  ["73O", "5LRG", "环状anabaenopeptin B中的高酪氨酸", "evidence-reviewed-residue"],
  ["73P", "5LRJ", "环状anabaenopeptin C中的氨甲酰赖氨酸样残基", "evidence-reviewed-residue"],
  ["7ID", "7LGJ", "蓝藻素Asp-Arg聚合物构件", "special-reference"],
  ["7N8", "5MHH", "工程脂质运载蛋白中的硼酸苯丙氨酸", "special-reference"],
  ["7O5", "6YA7", "酶底物肽中的硫酰化丝氨酸", "special-reference"],
  ["7OZ", "7PH1", "BPTI蛋白中的单氟氨基丁酸", "special-reference"],
  ["7XC", "5WXP", "uPA结合肽中的D-脒基苯丙氨酸", "evidence-reviewed-residue"],
  ["8LJ", "5URT", "胰岛素类似物中的脱氢脯氨酸", "evidence-reviewed-residue"],
  ["9IJ", "7SJJ", "PYP蛋白中的氰基苯丙氨酸", "special-reference"],
  ["9JC", "7QPB", "肽宏环中的喹啉醛折叠体单元", "special-reference"],
  ["9JV", "7QPB", "肽宏环中的喹啉酸折叠体单元", "special-reference"],
  ["9R1", "5VWY", "Bim肽中的氨基辛二酸残基", "evidence-reviewed-residue"],
  ["9R4", "5VWX", "Bim肽中的γ-谷氨酰甲基丙氨酸", "evidence-reviewed-residue"],
  ["9R7", "5VX0", "Bim肽中的γ-谷氨酰甘氨酸", "evidence-reviewed-residue"],
] as const;

export const pdbBatch9Residues = pdbBatch9EvidenceRecords.map(([ccd, pdb, name, componentClass]) => ({
  name,
  english: `CCD ${ccd}`,
  effect: componentClass === "evidence-reviewed-residue"
    ? "已确认作为非天然残基进入肽链；对构象、稳定性和渗透性的影响仍取决于具体序列与位置。"
    : "已确认出现在肽样、蛋白或其他聚合物体系中，但属于特殊构件或参考用途，不按普通肽合成单体推荐。",
  evidence: `PDB ${pdb}记录CCD ${ccd}；该结构证明确有使用，但不单独证明口服、增渗、商业可得或适合常规SPPS。`,
  paper: `PDB ${pdb} · CCD ${ccd}`,
  href: `https://www.rcsb.org/structure/${pdb}`,
  level: "实际使用证据" as const,
}));

export const pdbBatch9StructureMappings = Object.fromEntries(
  pdbBatch9EvidenceRecords.map(([ccd]) => [`CCD ${ccd}`, { ccd, label: `CCD ${ccd}` }]),
);

