import { pdbBatch8StructureMappings } from "./pdb-batch-8";
import { pdbBatch9StructureMappings } from "./pdb-batch-9";
import { pdbBatch10StructureMappings } from "./pdb-batch-10";

export type StructureRecord = {
  ccd: string;
  label: string;
};

// Only exact, stereochemically compatible CCD matches are listed here. Combined
// strategies and ambiguous patent building blocks intentionally have no image.
export const structuresByEnglish: Record<string, StructureRecord> = {
  "N-Me-D-Leu": { ccd: "MLU", label: "N-methyl-D-leucine" },
  "N-Me-Leu": { ccd: "MLE", label: "N-methyl-L-leucine" },
  "N-Me-Ile": { ccd: "IML", label: "N-methyl-L-isoleucine" },
  "N-Me-Ser": { ccd: "5JP", label: "N-methyl-L-serine" },
  "N-Me-Asp": { ccd: "SOQ", label: "N-methyl-L-aspartate" },
  "N-Me-Tyr": { ccd: "YNM", label: "N-methyl-L-tyrosine" },
  "N-Me-Lys": { ccd: "NMK", label: "N-methyl-L-lysine" },
  "N-Me-Phe": { ccd: "MEA", label: "N-methyl-L-phenylalanine" },
  "N-Me-Val": { ccd: "MVA", label: "N-methyl-L-valine" },
  "Sarcosine · Sar · N-Me-Gly": { ccd: "SAR", label: "sarcosine" },
  "D-Pro": { ccd: "DPR", label: "D-proline" },
  "D-Ala": { ccd: "DAL", label: "D-alanine" },
  "D-Val": { ccd: "DVA", label: "D-valine" },
  "D-Leu": { ccd: "DLE", label: "D-leucine" },
  "D-Ile": { ccd: "DIL", label: "D-isoleucine" },
  "D-Phe": { ccd: "DPN", label: "D-phenylalanine" },
  "Aib · α-aminoisobutyric acid": { ccd: "AIB", label: "α-aminoisobutyric acid" },
  "Sta · (3S,4S)-4-amino-3-hydroxy-6-methylheptanoic acid": { ccd: "STA", label: "statine" },
  "Aze · azetidine-2-carboxylic acid": { ccd: "02A", label: "L-azetidine-2-carboxylic acid" },
  "Nva · norvaline": { ccd: "NVA", label: "L-norvaline" },
  "Cha · cyclohexylalanine": { ccd: "ALC", label: "L-cyclohexylalanine" },
  "O-Me-Tyr · O-methyl-L-tyrosine": { ccd: "0A1", label: "O-methyl-L-tyrosine" },
  "(3S)-3-hydroxy-L-proline · 3-Hyp": { ccd: "HY3", label: "3-hydroxy-L-proline" },
  "3-Cl-Phe · 3-chloro-L-phenylalanine": { ccd: "FCL", label: "3-chloro-L-phenylalanine" },
  "Ac5c · 1-aminocyclopentane-1-carboxylic acid": { ccd: "AC5", label: "1-aminocyclopentane-1-carboxylic acid" },
  "(4R)-4-[(E)-2-butenyl]-4,N-dimethyl-L-threonine": { ccd: "BMT", label: "MeBmt" },
  "trans-4-F-Pro · (2S,4R)-4-fluoroproline": { ccd: "FP9", label: "trans-4-fluoro-L-proline" },
  "4-Hyp · trans-4-hydroxy-L-proline": { ccd: "HYP", label: "trans-4-hydroxy-L-proline" },
  "Orn · L-ornithine": { ccd: "ORN", label: "L-ornithine" },
  "Dap · L-2,3-diaminopropionic acid": { ccd: "DPP", label: "L-2,3-diaminopropionic acid" },
  "Hph · L-homophenylalanine": { ccd: "HPE", label: "L-homophenylalanine" },
  "2-Nal · 2-naphthylalanine": { ccd: "NAL", label: "L-2-naphthylalanine" },
  "N-Me-Ala / D-N-Me-Ala": { ccd: "MAA", label: "N-methyl-L-alanine" },
  "cis-4-F-Pro · (2S,4S)-4-fluoroproline": { ccd: "4FB", label: "cis-4-fluoro-L-proline" },
  "Tle / Tbg · tert-leucine / tert-butylglycine": { ccd: "TBG", label: "L-tert-leucine (tert-butylglycine)" },
  "5-F-Trp · 5-fluoro-L-tryptophan": { ccd: "FTR", label: "5-fluoro-L-tryptophan" },
  "2-Me-Pro · 2-methyl-L-proline": { ccd: "3WX", label: "2-methyl-L-proline" },
  "AmPhe · 3-(aminomethyl)-L-phenylalanine": { ccd: "A1CHA", label: "3-(aminomethyl)-L-phenylalanine" },
  "Abu · L-2-aminobutyric acid": { ccd: "ABA", label: "L-α-aminobutyric acid" },
  "D-Trp · D-tryptophan": { ccd: "DTR", label: "D-tryptophan" },
  "(1S,2S)-2-ACPC · trans-2-aminocyclopentanecarboxylic acid": { ccd: "XCP", label: "(1S,2S)-2-aminocyclopentanecarboxylic acid" },
  "D-Pen · D-penicillamine": { ccd: "LEI", label: "3-sulfanyl-D-valine (D-penicillamine)" },
  "L-Aad · L-2-aminoadipic acid": { ccd: "UN1", label: "L-2-aminoadipic acid" },
  "4CNW · 4-cyano-L-tryptophan": { ccd: "A1AWS", label: "4-cyano-L-tryptophan" },
  "AzAla · β-(1-azulenyl)-L-alanine": { ccd: "96Z", label: "β-(1-azulenyl)-L-alanine" },
  "pAzF · 4-azido-L-phenylalanine": { ccd: "4II", label: "4-azido-L-phenylalanine" },
  "D-Asn · D-asparagine": { ccd: "DSG", label: "D-asparagine" },
  "D-Asp · D-aspartic acid": { ccd: "DAS", label: "D-aspartic acid" },
  "D-Gln · D-glutamine": { ccd: "DGN", label: "D-glutamine" },
  "D-Met · D-methionine": { ccd: "MED", label: "D-methionine" },
  "D-Thr · D-threonine": { ccd: "DTH", label: "D-threonine" },
  "D-Tyr · D-tyrosine": { ccd: "DTY", label: "D-tyrosine" },
  "D-Ser · D-serine": { ccd: "DSN", label: "D-serine" },
  "Ac4c · 1-aminocyclobutane-1-carboxylic acid": { ccd: "192", label: "1-aminocyclobutane-1-carboxylic acid" },
  "Nle · L-norleucine": { ccd: "NLE", label: "L-norleucine" },
  "D-Glu · D-glutamic acid": { ccd: "DGL", label: "D-glutamic acid" },
  "D-Arg · D-arginine": { ccd: "DAR", label: "D-arginine" },
  "Dab · L-2,4-diaminobutyric acid": { ccd: "DAB", label: "L-2,4-diaminobutyric acid" },
  "Dhb · (2Z)-2-aminobut-2-enoic acid": { ccd: "DBU", label: "dehydrobutyrine" },
  "Dha · dehydroalanine": { ccd: "DHA", label: "dehydroalanine" },
  "D-Abu · D-alpha-aminobutyric acid": { ccd: "DBB", label: "D-alpha-aminobutyric acid" },
  "D-Hpg · (2R)-amino(4-hydroxyphenyl)ethanoic acid": { ccd: "GHP", label: "D-4-hydroxyphenylglycine" },
  "Dpg · (2S)-amino(3,5-dihydroxyphenyl)ethanoic acid": { ccd: "3FG", label: "3,5-dihydroxyphenylglycine" },
  "Cl-HyTyr-L · (βR)-3-chloro-β-hydroxy-L-tyrosine": { ccd: "OMY", label: "3-chloro-beta-hydroxy-L-tyrosine" },
  "Cl-HyTyr-D · (βR)-3-chloro-β-hydroxy-D-tyrosine": { ccd: "OMZ", label: "3-chloro-beta-hydroxy-D-tyrosine" },
  "β3-Aad · (3S)-3-aminohexanedioic acid": { ccd: "B3E", label: "beta3-aminoadipic acid" },
  "β3-hLeu · (3S)-3-amino-5-methylhexanoic acid": { ccd: "B3L", label: "beta3-homoleucine" },
  "β-Me-D-Asp · 3-methyl-beta-D-aspartic acid": { ccd: "ACB", label: "3-methyl-beta-D-aspartic acid" },
  "L-allo-Thr · L-allothreonine": { ccd: "ALO", label: "L-allothreonine" },
  "L-Pip · (2S)-piperidine-2-carboxylic acid": { ccd: "YCP", label: "L-pipecolic acid" },
  "N-Me-Cys · N-methyl-L-cysteine": { ccd: "NCY", label: "N-methyl-L-cysteine" },
  "D-allo-Thr · D-allothreonine": { ccd: "2TL", label: "D-allothreonine" },
  "Cit · L-citrulline": { ccd: "CIR", label: "L-citrulline" },
  "Lys(Me) · N6-methyl-L-lysine": { ccd: "MLZ", label: "N6-methyl-L-lysine" },
  "β-HyTyr · (βR)-β-hydroxy-L-tyrosine": { ccd: "OMX", label: "beta-hydroxy-L-tyrosine" },
  "N-Me-4-OH-Leu · N-methyl-4-hydroxy-L-leucine": { ccd: "MHL", label: "N-methyl-4-hydroxy-L-leucine" },
  "MeDhb · N-methyldehydrobutyrine": { ccd: "MDH", label: "N-methyldehydrobutyrine" },
  "Kyn · L-kynurenine": { ccd: "KYN", label: "L-kynurenine" },
  "Oic · octahydroindole-2-carboxylic acid": { ccd: "OIC", label: "octahydroindole-2-carboxylic acid" },
  "CbAla · 3-cyclobutyl-L-alanine": { ccd: "2JH", label: "3-cyclobutyl-L-alanine" },
  "α-Me-D-Nle · 2-methyl-D-norleucine": { ccd: "2JN", label: "2-methyl-D-norleucine" },
  "D-Dap · 3-amino-D-alanine": { ccd: "2RA", label: "3-amino-D-alanine" },
  "D-Ethynoxy-Pro · (4S)-4-(ethynyloxy)-D-proline": { ccd: "45W", label: "4-ethynyloxy-D-proline" },
  "N-Me-Hpg · (2S)-(4-hydroxyphenyl)(methylamino)ethanoic acid": { ccd: "5PG", label: "N-methyl-4-hydroxyphenylglycine" },
  "N-Et-Val · N-ethyl-L-valine": { ccd: "66E", label: "N-ethyl-L-valine" },
  "N-Me-Cpg · (2S)-2-cyclopentyl-2-(methylamino)ethanoic acid": { ccd: "7VN", label: "N-methylcyclopentylglycine" },
  "LUNA18-7WC · (3S)-4-(dimethylamino)-3-(methylamino)-4-oxobutanoic acid": { ccd: "7WC", label: "N-methyl dimethylamide residue 7WC" },
  "4-COOH-D-Phe · 4-carboxy-D-phenylalanine": { ccd: "99Y", label: "4-carboxy-D-phenylalanine" },
  "MeNle-9KK · N-methyl norleucine": { ccd: "9KK", label: "N-methyl norleucine" },
  "Cha-Piz · (2S)-4-cyclohexylcarbonylpiperazine-2-carboxylic acid": { ccd: "A1JAL", label: "4-cyclohexylcarbonylpiperazine-2-carboxylic acid" },
  "PhCha-D-Ala · (R)-2-amino-3-(4-phenylcyclohexyl)propanoic acid": { ccd: "BIF", label: "4-phenylcyclohexyl-D-alanine" },
  "D-Dpg · (2R)-amino(3,5-dihydroxyphenyl)acetic acid": { ccd: "D3P", label: "D-3,5-dihydroxyphenylglycine" },
  "D-Nle · D-norleucine": { ccd: "DNE", label: "D-norleucine" },
  "4-Oxo-Pro · 4-oxoproline": { ccd: "DPL", label: "4-oxoproline" },
  "N-Me-D-Ser · N-methyl-D-serine": { ccd: "DSE", label: "N-methyl-D-serine" },
  "6-F-D-Trp · 6-fluoro-D-tryptophan": { ccd: "E03", label: "6-fluoro-D-tryptophan" },
  "3-OH-5-Me-Pro · trans-3-hydroxy-5-methylproline": { ccd: "H5M", label: "trans-3-hydroxy-5-methylproline" },
  "N-Me-Cha · 3-cyclohexyl-N-methyl-L-alanine": { ccd: "H7V", label: "3-cyclohexyl-N-methyl-L-alanine" },
  "β-L-Asp · beta-L-aspartic acid": { ccd: "IAS", label: "beta-L-aspartic acid" },
  "cis-ACBC · cis-3-aminocyclobutane carboxylic acid": { ccd: "II7", label: "cis-3-aminocyclobutane carboxylic acid" },
  "S-Me-Sar · (2-S-methyl) sarcosine": { ccd: "MSA", label: "S-methyl sarcosine" },
  "N-Me-D-Val · (2R)-3-methyl-2-(methylamino)butanoic acid": { ccd: "MV9", label: "N-methyl-D-valine" },
  "N-Cpm-Gly · N-cyclopropylmethylglycine": { ccd: "NMC", label: "N-cyclopropylmethylglycine" },
  "D-Orn · D-ornithine": { ccd: "ORD", label: "D-ornithine" },
  "5-Me-4-Oxo-Pro · cis-5-methyl-4-oxoproline": { ccd: "POM", label: "cis-5-methyl-4-oxoproline" },
  "α-Et-D-Nle · (2R)-2-amino-2-ethyloctanoic acid": { ccd: "R6E", label: "alpha-ethyl-D-norleucine" },
  "p-CF3-D-Phe · 4-(trifluoromethyl)-D-phenylalanine": { ccd: "TDF", label: "4-trifluoromethyl-D-phenylalanine" },
  "N-MeCO-Thr · N-methylcarbonylthreonine": { ccd: "THC", label: "N-methylcarbonylthreonine" },
  "4-EtO-Pro · (4R)-4-ethoxy-L-proline": { ccd: "ZNY", label: "4-ethoxy-L-proline" },
  "D-allo-Ile · D-alloisoleucine": { ccd: "28J", label: "D-alloisoleucine" },
  "3-Cl-D-Tyr · 3-chloro-D-tyrosine": { ccd: "3MY", label: "3-chloro-D-tyrosine" },
  "D-Dab · (2R)-2,4-diaminobutanoic acid": { ccd: "4FO", label: "D-2,4-diaminobutyric acid" },
  "D-2-Nal · (2R)-2-amino-3-(naphthalen-2-yl)propanoic acid": { ccd: "4J2", label: "D-2-naphthylalanine" },
  "Octanoyl-D-Val · N-octanoyl-D-valine": { ccd: "4N3", label: "N-octanoyl-D-valine" },
  "Achc-4 · 4-aminocyclohexane-1-carboxylic acid": { ccd: "6RK", label: "4-aminocyclohexane-1-carboxylic acid" },
  "3-Me-D-His · 3-methyl-D-histidine": { ccd: "A1AZ2", label: "3-methyl-D-histidine" },
  "Pasireotide-Pro · (2S,4R)-4-(2-aminoethylcarbamoyloxy)pyrrolidine-2-carboxylic acid": { ccd: "A1D5E", label: "pasireotide proline residue" },
  "D-Tic · (3R)-1,2,3,4-tetrahydroisoquinoline-3-carboxylic acid": { ccd: "A1EJL", label: "D-tetrahydroisoquinoline-3-carboxylic acid" },
  "O-Et-D-Tyr · O-ethyl-D-tyrosine": { ccd: "A1EQM", label: "O-ethyl-D-tyrosine" },
  "β3-hSer · (3R)-3-amino-4-hydroxybutanoic acid": { ccd: "B3S", label: "beta3-homoserine" },
  "4-Br-D-Phe · 4-bromo-D-phenylalanine": { ccd: "BF7", label: "4-bromo-D-phenylalanine" },
  "Chg · cyclohexylglycine": { ccd: "CHG", label: "cyclohexylglycine" },
  "Cpi · 6-carboxypiperidine": { ccd: "CPI", label: "6-carboxypiperidine" },
  "4-Cl-D-Phe · 4-chloro-D-phenylalanine": { ccd: "D0C", label: "4-chloro-D-phenylalanine" },
  "Mdha · N-methyl-alpha-beta-dehydroalanine": { ccd: "DAM", label: "N-methyldehydroalanine" },
  "D-His · D-histidine": { ccd: "DHI", label: "D-histidine" },
  "3-OH-D-Val · 3-hydroxy-D-valine": { ccd: "DHV", label: "3-hydroxy-D-valine" },
  "D-Iva · D-isovaline": { ccd: "DIV", label: "D-isovaline" },
  "N-Me-D-Nle · N-methyl-D-norleucine": { ccd: "DNM", label: "N-methyl-D-norleucine" },
  "N-Me-L-Trp · N-methyl-L-tryptophan": { ccd: "E9M", label: "N-methyl-L-tryptophan" },
  "N-Me-L-His · N-methyl-L-histidine": { ccd: "E9V", label: "N-methyl-L-histidine" },
  "5-OH-N-Me-Leu · (4S)-5-hydroxy-N-methyl-L-leucine": { ccd: "F7S", label: "5-hydroxy-N-methyl-L-leucine" },
  "N-Me-D-Gln · N2-methyl-D-glutamine": { ccd: "HJV", label: "N2-methyl-D-glutamine" },
  "Cyclomarin-HyMeLeu · (4R)-5-hydroxy-N-methyl-L-leucine": { ccd: "WLU", label: "cyclomarin hydroxy-N-methylleucine" },
  "N-Me-Nva · N-methyl-L-norvaline": { ccd: "A1L7N", label: "N-methyl-L-norvaline" },
  "N-Me-CbAla · (2S)-3-cyclobutyl-2-(methylamino)propanoic acid": { ccd: "A1L7L", label: "N-methyl-3-cyclobutyl-L-alanine" },
  "Api-4 · 4-aminopiperidine-4-carboxylic acid": { ccd: "A1L9X", label: "4-aminopiperidine-4-carboxylic acid" },
  "Cih-Hy-D-Tyr · (2R,3S)-2-amino-3-(4-hydroxyphenyl)-3-hydroxypropanoic acid": { ccd: "A1D5P", label: "cihanmycin beta-hydroxy-D-tyrosine" },
  "α-Me-Glu · alpha-methyl-L-glutamic acid": { ccd: "GAM", label: "alpha-methyl-L-glutamic acid" },
  "HomoPhe · 2-amino-4-phenylbutyric acid": { ccd: "HMF", label: "homophenylalanine" },
  "Hy-N-Me-D-Asn · (3R)-3-hydroxy-N-methyl-D-asparagine": { ccd: "HTN", label: "3-hydroxy-N-methyl-D-asparagine" },
  "β-Hy-D-Tyr · beta-hydroxy-D-tyrosine": { ccd: "HTY", label: "beta-hydroxy-D-tyrosine" },
  "4-AmPro · 4-aminoproline": { ccd: "JKH", label: "4-aminoproline" },
  "D-Hcy · D-homocysteine": { ccd: "KCY", label: "D-homocysteine" },
  "D-3-OH-Leu · D-3-hydroxyleucine": { ccd: "KJW", label: "D-3-hydroxyleucine" },
  "5-Me-D-Nle · 5-methyl-D-norleucine": { ccd: "KW4", label: "5-methyl-D-norleucine" },
  "N-Me-Asn · N-methyl-L-asparagine": { ccd: "MEN", label: "N-methyl-L-asparagine" },
  "N-Me-D-Asn · N-methyl-D-asparagine": { ccd: "MND", label: "N-methyl-D-asparagine" },
  "4-Me-Pro · (4R)-4-methyl-L-proline": { ccd: "MP8", label: "4-methyl-L-proline" },
  "N-Me-S-secBu-Cys · N-methyl-S-[(1R)-1-methylpropyl]-L-cysteine": { ccd: "NYB", label: "N-methyl-S-sec-butyl-L-cysteine" },
  "MeI-Thr · N-methylidene-L-threonine": { ccd: "NZC", label: "N-methylidene-L-threonine" },
  "4-MeO-N-Me-Trp · 4-methoxy-N-methyl-L-tryptophan": { ccd: "O7D", label: "4-methoxy-N-methyl-L-tryptophan" },
  "N-Me-β-Hy-His · gamma-N-methyl-beta-hydroxyhistidine": { ccd: "OGC", label: "gamma-N-methyl-beta-hydroxyhistidine" },
  "4-Cha-Pro · (4S)-4-cyclohexyl-L-proline": { ccd: "PH6", label: "4-cyclohexyl-L-proline" },
  "1-MeO-N-Me-Trp · 1-methoxy-N-methyl-L-tryptophan": { ccd: "SZF", label: "1-methoxy-N-methyl-L-tryptophan" },
  "D-Tle · (2R)-2-amino-3,3-dimethylbutanoic acid": { ccd: "TDD", label: "D-tert-leucine" },
  "4-Et-Pro · trans-4-ethyl-L-proline": { ccd: "V3C", label: "trans-4-ethyl-L-proline" },
  "Dab(2R,3R) · (2R,3R)-2,3-diaminobutanoic acid": { ccd: "VDL", label: "(2R,3R)-2,3-diaminobutanoic acid" },
  "N-Me-L-allo-Ile · N-methyl-L-alloisoleucine": { ccd: "WZJ", label: "N-methyl-L-alloisoleucine" },
  "Ustiloxin-HyMeTyr · (betaR)-beta,3-dihydroxy-N-methyl-L-tyrosine": { ccd: "0EA", label: "ustiloxin beta,3-dihydroxy-N-methyl-L-tyrosine" },
  "Dityromycin-HyMeOTyr · (betaR)-beta-hydroxy-O-methyl-L-tyrosine": { ccd: "2R3", label: "dityromycin beta-hydroxy-O-methyl-L-tyrosine" },
  "γ-Me-Aib(S) · (4S)-2,4-dimethyl-L-norleucine": { ccd: "5GM", label: "(4S)-2,4-dimethyl-L-norleucine" },
  "γ-Me-Aib(R) · (4R)-2,4-dimethyl-L-norleucine": { ccd: "66D", label: "(4R)-2,4-dimethyl-L-norleucine" },
  "β3-hMet · (3R)-3-amino-5-(methylsulfanyl)pentanoic acid": { ccd: "B3M", label: "beta3-homomethionine" },
  "L-threo-β-HyPhe · (2S,3S)-beta-hydroxyphenylalanine": { ccd: "BB8", label: "L-threo-beta-hydroxyphenylalanine" },
  "β3-hIle · (3R,4S)-3-amino-4-methylhexanoic acid": { ccd: "BIL", label: "beta3-homoisoleucine" },
  "Helioferin-Hkaa · (2S,4S,6S)-2-amino-6-hydroxy-4-methyl-8-oxodecanoic acid": { ccd: "BZK", label: "helioferin hydroxy-keto amino acid" },
  "MeBmt · 3-hydroxy-4,4-dimethyl-2-(methylamino)-6-octenoic acid": { ccd: "DMT", label: "MeBmt" },
  "β-HyPhe(2S,3R) · (2S,3R)-beta-hydroxyphenylalanine": { ccd: "H14", label: "(2S,3R)-beta-hydroxyphenylalanine" },
  "β-HyLeu · (2S,3R)-2-amino-3-hydroxy-4-methylpentanoic acid": { ccd: "HL2", label: "beta-hydroxy-L-leucine" },
  "β-hArg · beta-homoarginine": { ccd: "HMR", label: "beta-homoarginine" },
  "β3-hTrp · (3S)-3-amino-4-(1H-indol-3-yl)butanoic acid": { ccd: "HT7", label: "beta3-homotryptophan" },
  "Rufomycin-Trp · 1-[(3R)-3-hydroxy-2-methylbutan-2-yl]-L-tryptophan": { ccd: "F7P", label: "rufomycin substituted tryptophan" },
  "β-Akpa · (3S)-3-amino-4-oxo-7-phenylheptanoic acid": { ccd: "FPR", label: "beta-amino keto-acid inhibitor residue" },
  "N-Me-Glu · N-methyl-L-glutamic acid": { ccd: "EME", label: "N-methyl-L-glutamic acid" },
  "Δ4,5-Leu · 4,5-dehydro-L-leucine": { ccd: "EO2", label: "4,5-dehydro-L-leucine" },
  "β3-Pro · beta3-proline": { ccd: "EOE", label: "beta3-proline" },
  "3-OH-L-Val · 3-hydroxy-L-valine": { ccd: "HVA", label: "3-hydroxy-L-valine" },
  "D-allylglycine · (2R)-2-aminopent-4-enoic acid": { ccd: "DYL", label: "D-allylglycine" },
  "β-Ph-Phe · beta-phenyl-L-phenylalanine": { ccd: "2GX", label: "beta-phenyl-L-phenylalanine" },
  "L-Cpg · (2S)-amino(cyclopentyl)ethanoic acid": { ccd: "2KY", label: "L-cyclopentylglycine" },
  "β3-hAla · (3S)-3-aminobutanoic acid": { ccd: "B3A", label: "beta3-homoalanine" },
  "β3-hLys · (3S)-3,7-diaminoheptanoic acid": { ccd: "B3K", label: "beta3-homolysine" },
  "β3-hGln · (3S)-3,6-diamino-6-oxohexanoic acid": { ccd: "B3Q", label: "beta3-homoglutamine" },
  "Ustiloxin-HyIle · (2S,3R)-2-amino-3-methyl-3-hydroxypentanoic acid": { ccd: "0E5", label: "ustiloxin hydroxyisoleucine" },
  "Dityromycin-MeDhaTyr · (2Z)-3-(4-hydroxyphenyl)-2-(methylamino)prop-2-enoic acid": { ccd: "2QY", label: "N-methyldehydrotyrosine" },
  "Dityromycin-Me2Thr · N,N-dimethyl-L-threonine": { ccd: "2QZ", label: "N,N-dimethyl-L-threonine" },
  "Dityromycin-EpoxyDha · (2E)-2-amino-4-hydroxy-3-[(2R)-oxiran-2-yl]but-2-enoic acid": { ccd: "2R1", label: "dityromycin epoxy dehydroamino acid" },
  "3-Me-Asp · (2S,3S)-3-methylaspartic acid": { ccd: "2AS", label: "3-methyl-L-aspartic acid" },
  "Chp · 3-chloro-4-hydroxyphenylglycine": { ccd: "CHP", label: "3-chloro-4-hydroxyphenylglycine" },
  "Hpg · (2S)-amino(4-hydroxyphenyl)acetic acid": { ccd: "D4P", label: "4-hydroxyphenylglycine" },
  "β-HyAsn · beta-hydroxyasparagine": { ccd: "AHB", label: "beta-hydroxyasparagine" },
  "GE2270-BB6 · (2Z)-2-amino-3-sulfanylbut-2-enoic acid": { ccd: "BB6", label: "GE2270 sulfur-containing dehydroamino acid BB6" },
  "GE2270-BB7 · (2Z)-2-amino-4-methoxy-3-sulfanylbut-2-enoic acid": { ccd: "BB7", label: "GE2270 sulfur-containing dehydroamino acid BB7" },
  "GE2270-BB9 · (2Z)-2-amino-3-sulfanylprop-2-enoic acid": { ccd: "BB9", label: "GE2270 sulfur-containing dehydroamino acid BB9" },
  "GE2270-MH6 · 3-hydroxy-2-iminopropanoic acid": { ccd: "MH6", label: "GE2270 modified serine residue" },
  "Quinomycin-Cpc · 2-methyl-1-methylaminocyclopropanecarboxylic acid": { ccd: "CPC", label: "quinomycin N-methylaminocyclopropanecarboxylic acid" },
  "Polytheonamide-Me-allo-Ile · 3-methyl-L-alloisoleucine": { ccd: "I2M", label: "3-methyl-L-alloisoleucine" },
  "Polytheonamide-MeGln · (3S)-3-methyl-L-glutamine": { ccd: "LMQ", label: "3-methyl-L-glutamine" },
  "Polytheonamide-MsoVal · 3-[(R)-methylsulfinylmethyl]-L-valine": { ccd: "M2S", label: "methylsulfinylmethyl-L-valine" },
  "Rufomycin-EnAA · (2S,4E)-2-aminohex-4-enoic acid": { ccd: "F7V", label: "rufomycin alkenyl amino acid" },
  "αβ-foldamer-Aje · (3S,4R)-4-amino-1-(3-carboxypropanoyl)pyrrolidine-3-carboxylic acid": { ccd: "AJE", label: "alpha/beta-foldamer cyclic diacid residue" },
  "αβ-foldamer-MH8 · (2S)-2-amino-2-methylhept-6-enoic acid": { ccd: "MH8", label: "alpha-methyl alkenyl amino acid" },
  "Dalbavancin-Hcl · chlorodihydroxyphenylglycine": { ccd: "HCL", label: "dalbavancin chlorodihydroxyphenylglycine" },
  "Dalbavancin-NMe-D-Hpg · (2R)-2-(4-hydroxyphenyl)-2-(methylamino)ethanoic acid": { ccd: "HGM", label: "N-methyl-D-hydroxyphenylglycine" },
  "Dalbavancin-DhMpg · amino(3,5-dihydroxy-4-methylphenyl)ethanoic acid": { ccd: "MP4", label: "dalbavancin dihydroxymethylphenylglycine" },
  "β-Tyr · beta-tyrosine": { ccd: "IB9", label: "beta-tyrosine" },
  "L-End · enduracididine": { ccd: "EI4", label: "L-enduracididine" },
  "Cyclosporin-Me2Nle · 4,N-dimethylnorleucine": { ccd: "MNL", label: "4,N-dimethylnorleucine" },
  "β-Me-Phe · (betaS)-beta-methyl-L-phenylalanine": { ccd: "41H", label: "beta-methyl-L-phenylalanine" },
  "β3-hAbu · (4S)-4-aminopentanoic acid": { ccd: "0W6", label: "beta3-homo-2-aminobutyric acid" },
  "β3-hLeu(R) · (3R)-3-amino-4-methylpentanoic acid": { ccd: "1VR", label: "beta3-homoleucine (R)" },
  "2-Me-Leu · 2-methylleucine": { ccd: "2ML", label: "2-methylleucine" },
  "TfNva · (2S)-2-amino-4,4,4-trifluorobutanoic acid": { ccd: "3EG", label: "trifluoronorvaline" },
  "4-HyGlu · (2S,4S)-2-amino-4-hydroxypentanedioic acid": { ccd: "3GL", label: "4-hydroxy-L-glutamic acid" },
  "4-iPrO-Pro · (3S)-3-(propan-2-yloxy)-L-proline": { ccd: "3PX", label: "4-isopropoxy-L-proline" },
  "4-Me-Phe · 4-methyl-L-phenylalanine": { ccd: "4PH", label: "4-methyl-L-phenylalanine" },
  "5-HyTrp · 5-hydroxy-L-tryptophan": { ccd: "4PQ", label: "5-hydroxy-L-tryptophan" },
  "Dmoa · (2S)-2-amino-7,7-dimethyloctanoic acid": { ccd: "4WQ", label: "7,7-dimethyloctanoic amino acid" },
  "5-Cl-Trp · 5-chloro-L-tryptophan": { ccd: "5CW", label: "5-chloro-L-tryptophan" },
  "6-Cl-Trp · 6-chloro-L-tryptophan": { ccd: "6CW", label: "6-chloro-L-tryptophan" },
  "Hfl · 5,5,5,5′,5′,5′-hexafluoro-L-leucine": { ccd: "6FL", label: "hexafluoro-L-leucine" },
  "MeThz · 2-methyl-1,3-thiazole-5-carboxylic acid": { ccd: "6V9", label: "methylthiazole carboxylic acid" },
  "L-Iva · L-isovaline": { ccd: "6ZS", label: "L-isovaline" },
  "O-Me-Ser · O-methyl-L-serine": { ccd: "7C9", label: "O-methyl-L-serine" },
  "N-Me-4-Cl-Phe · (2S)-3-(4-chlorophenyl)-2-(methylamino)propanoic acid": { ccd: "7T2", label: "N-methyl-4-chloro-L-phenylalanine" },
  "N-Et-4-Me-Phe · (2S)-2-(ethylamino)-3-(4-methylphenyl)propanoic acid": { ccd: "7VU", label: "N-ethyl-4-methyl-L-phenylalanine" },
  "D-pGlu · (2R)-5-oxopyrrolidine-2-carboxylic acid": { ccd: "7YO", label: "D-pyroglutamic acid" },
  "N-Et-Gln · N-ethyl-L-glutamine": { ccd: "85G", label: "N-ethyl-L-glutamine" },
  "N-Pr-Gln · N-propyl-L-glutamine": { ccd: "85J", label: "N-propyl-L-glutamine" },
  "Rufomycin-BuO-MeLeu · (4S)-5-butoxy-N-methyl-L-leucine": { ccd: "A1A5T", label: "rufomycin butoxy N-methylleucine" },
  "3-Me-Iva · 3-methyl-L-isovaline": { ccd: "A1A8T", label: "3-methyl-L-isovaline" },
  "Caspofungin-HyOrn-Aee · (4R,5R)-5-amino-N5-(2-aminoethyl)-4-hydroxy-L-ornithine": { ccd: "A1CHS", label: "caspofungin aminoethyl hydroxyornithine" },
  "Caspofungin-DHyHpt · (4S)-4-hydroxy-4-(4-hydroxyphenyl)-L-threonine": { ccd: "A1CHT", label: "caspofungin dihydroxyhomotyrosine" },
  "3-HyOrn · (3R)-3-hydroxy-L-ornithine": { ccd: "A1CHU", label: "3-hydroxy-L-ornithine" },
  "D-Cpg · (2R)-2-amino-2-cyclopentylethanoic acid": { ccd: "A1EAK", label: "D-cyclopentylglycine" },
  "MeHyIva · N-methyl-3-hydroxyisovaline": { ccd: "A1L3I", label: "N-methyl-hydroxyisovaline" },
  "OxoPip-Ala · (2S)-2-amino-3-[(3S)-2-oxopiperidin-3-yl]propanoic acid": { ccd: "A1L7K", label: "oxopiperidinyl alanine" },
  "St3-R · (Z,2S)-2-amino-2-methyloct-6-enoic acid": { ccd: "A1MDN", label: "St3-R stapling amino acid" },
  "β2-hLeu · (2S)-2-(aminomethyl)-4-methylpentanoic acid": { ccd: "A1MF6", label: "beta2-homoleucine" },
  "D-β3-hAla · (3R)-3-aminobutanoic acid": { ccd: "A1MFI", label: "D-beta3-homoalanine" },
  "Ahoh · amino-hydroxyheptanoic acid": { ccd: "AHH", label: "amino-hydroxyheptanoic acid" },
  "β3-hGlu · 3-aminopentanedioic acid": { ccd: "B3D", label: "beta3-homoglutamic acid" },
  "β3-hThr · 3-amino-2,3,5-trideoxy-D-threo-pentonic acid": { ccd: "B3T", label: "beta3-homothreonine" },
  "β3-hAsn · (3S)-3,5-diamino-5-oxopentanoic acid": { ccd: "B3X", label: "beta3-homoasparagine" },
  "β3-hTyr · (3S)-3-amino-4-(4-hydroxyphenyl)butanoic acid": { ccd: "B3Y", label: "beta3-homotyrosine" },
  "β3-hSer · beta-3-serine": { ccd: "BSE", label: "beta3-homoserine" },
  "4-Cl-Thr · 4-chlorothreonine": { ccd: "CTH", label: "4-chlorothreonine" },
  "Dmt · 2,6-dimethyl-L-tyrosine": { ccd: "DI7", label: "2,6-dimethyl-L-tyrosine" },
  "Tic · (3S)-1,2,3,4-tetrahydroisoquinoline-3-carboxylic acid": { ccd: "DI8", label: "tetrahydroisoquinoline carboxylic acid" },
  "N,N-Me2-Asn · N4,N4-dimethyl-asparagine": { ccd: "DMH", label: "N,N-dimethylasparagine" },
  "3,3-Me2-Asp · 3,3-dimethylaspartic acid": { ccd: "DMK", label: "3,3-dimethylaspartic acid" },
  "D-Pra · (2R)-2-aminopent-4-ynoic acid": { ccd: "F9D", label: "D-propargylglycine" },
  "N-Me-Gln · N2-methyl-L-glutamine": { ccd: "GNC", label: "N-methyl-L-glutamine" },
  "Hcy · 2-amino-4-mercaptobutyric acid": { ccd: "HCS", label: "homocysteine" },
  "β3-hArg · (3S)-3-amino-6-guanidinohexanoic acid": { ccd: "HR7", label: "beta3-homoarginine" },
  "Igl · alpha-amino-2-indanacetic acid": { ccd: "IGL", label: "indan glycine" },
  "N-Me-Arg · N2-methyl-L-arginine": { ccd: "MMO", label: "N-methyl-L-arginine" },
  "N-Me-Phg · N-methyl-alpha-phenylglycine": { ccd: "MPQ", label: "N-methylphenylglycine" },
  ...pdbBatch8StructureMappings,
  ...pdbBatch9StructureMappings,
  ...pdbBatch10StructureMappings,
};

export const additionalStructuresByEnglish: Record<string, StructureRecord[]> = {
  "N-Me-Ala / D-N-Me-Ala": [{ ccd: "33X", label: "N-methyl-D-alanine" }],
  "D-Glu · D-glutamic acid": [{ ccd: "FGA", label: "D-glutamic acid (gamma-linking CCD entry)" }],
};

export const structureNotesByEnglish: Record<string, string> = {
  "N-Me-Thr": "CCD 中未找到与 N-甲基-L-苏氨酸立体化学完全一致的单体；O7A 对应 N-甲基-L-别苏氨酸，不能替代展示。",
  "N-Me-D-Trp": "CCD 的 E9M 对应 N-甲基-L-色氨酸；当前条目为 D-构型，因此不使用该图。",
  "β-homoproline · β-HPro": "原始来源使用 β-HPro 缩写，但当前记录未给出可与 CCD 唯一匹配的绝对构型。",
  "(1R,2S)-2-ACPC · β¹": "CCD 中可检索到其他 2-氨基环戊烷羧酸立体异构体，但未找到与 (1R,2S) 完全一致的条目。",
  "(1S,2S)-2-ACHC · β²": "未找到与条目所示绝对构型完全一致的独立 CCD 单体。",
  "NLeu peptoid · N-isobutylglycine": "该 peptoid 单体尚未找到可唯一对应的 CCD 条目。",
  "Pye · N,N-pyrrolidinylglutamine": "Pye 是论文设计的侧链-主链氢键构件，尚未找到可唯一对应的 CCD 单体。",
  "4-AmPhe · 4-(aminomethyl)-L-phenylalanine": "CCD 可检索到 D-构型 4-AmPhe（1G8），但当前条目为 L-构型，不能混用。",
  "Pal · pyridylalanine": "Pal 可指 3-或 4-吡啶基丙氨酸；当前来源记录未在条目名称中固定异构体，因此不配唯一结构。",
  "N-substituted 5-F-Trp": "该构件同时包含吲哚 N-取代与骨架交联，不能用游离 5-F-Trp（FTR）代表。",
  "D-Dap(tail) · side-chain-acylated D-2,3-diaminopropionic acid": "该记录指侧链已酰化并连接增溶尾部的构件，不是游离 D-Dap 单体。",
  "4-CF₃-Hph / 3,5-F₂-4-CF₃-Hph": "一条记录包含两个不同芳香取代物，且尚无两个结构均可精确核对的 CCD 条目。",
  "hydroxy-acid / depsipeptide substitution": "这是酰胺→酯的骨架替换策略，不对应一种固定氨基酸单体。",
  "thioamide substitution": "这是 C=O→C=S 的骨架替换策略，不对应一种固定氨基酸单体。",
  "N-(2-naphthylmethylene)-trans-4-amino-L-proline building block": "原文构件包含特定的 2-萘亚甲基取代；当前未找到可同时匹配骨架、取代位置和立体化学的唯一 CCD 条目。",
  "pCAP · phosphocoumaryl aminopropionic acid": "pCAP 是带磷酸香豆素报告基团的功能性氨基酸样构件；当前未找到可与原文结构唯一对应的 CCD 条目。",
  "AllocK · Nε-Alloc-L-lysine": "当前 CCD 结构目录未找到与 Nε-Alloc-L-赖氨酸完全一致的独立单体。",
  "AlkynK · Nε-(prop-2-yn-1-yloxycarbonyl)-L-lysine": "当前 CCD 结构目录未找到与该 Nε-炔丙氧羰基取代完全一致的独立单体。",
  "pIF · 4-iodo-L-phenylalanine": "CCD 中有 4-碘-D-苯丙氨酸及其他碘代异构体，但未找到可明确确认为 4-碘-L-苯丙氨酸的唯一条目。",
  "CbzK · Nε-carbobenzyloxy-L-lysine": "当前 CCD 结构目录未找到与 Nε-Cbz-L-赖氨酸完全一致的独立单体。",
  "O2beY · O-(2-bromoethyl)-L-tyrosine": "当前 CCD 结构目录未找到与 O-(2-溴乙基)-L-酪氨酸完全一致的独立单体。",
  "pVsaF · p-(vinylsulfonamido)-L-phenylalanine": "当前 CCD 结构目录未找到侧链、位置和立体化学均完全一致的唯一条目。",
  "pAaF · p-(acrylamido)-L-phenylalanine": "当前 CCD 结构目录未找到侧链、位置和立体化学均完全一致的唯一条目。",
  "pCaaF · p-(2-chloroacetamido)-L-phenylalanine": "当前 CCD 结构目录未找到侧链、位置和立体化学均完全一致的唯一条目。",
  "O4bbY · O-(4-bromobutyl)-L-tyrosine": "当前 CCD 结构目录未找到与 O-(4-溴丁基)-L-酪氨酸完全一致的独立单体。",
  "L-Piz · L-piperazic acid": "当前 CCD 目录中的哌嗪羧酸条目均带额外取代，不能代替未取代 L-哌嗪酸。",
  "D-Piz · D-piperazic acid": "当前 CCD 目录未找到可唯一对应未取代 D-哌嗪酸的条目。",
  "MeNva · N-methyl-L-norvaline": "当前 CCD 结构目录未找到与 N-甲基-L-正缬氨酸完全一致的独立单体。",
  "MeNle · N-methyl-L-norleucine": "当前 CCD 结构目录未找到与 N-甲基-L-正亮氨酸完全一致的独立单体。",
  "MeYm · N-methyl-4-methoxy-L-phenylalanine": "当前 CCD 结构目录未找到同时匹配 N-甲基化、对位甲氧基和 L-构型的唯一单体。",
  "D-β3Phg · D-beta3-phenylglycine": "CCD 中存在 (3S)-3-氨基-3-苯基丙酸，但 D-β³Phg 的命名与绝对构型未完成唯一核对，因此不强行映射。",
  "ClAc-D-Tyr · N-chloroacetyl-D-tyrosine": "这是 N 端氯乙酰化起始构件，不能用游离 D-Tyr（DTY）的结构代替。",
  "ClAc-L-Tyr · N-chloroacetyl-L-tyrosine": "这是 N 端氯乙酰化起始构件，不能用游离 L-Tyr 的结构代替。",
};

export const getStructures = (english: string): StructureRecord[] => {
  const primary = structuresByEnglish[english];
  return primary ? [primary, ...(additionalStructuresByEnglish[english] ?? [])] : [];
};

export const ccdImageUrl = (ccd: string) => `https://www.ebi.ac.uk/pdbe/static/files/pdbechem_v2/${ccd}_500.svg`;
export const ccdEntryUrl = (ccd: string) => `https://www.rcsb.org/ligand/${ccd}`;
